{
 "title": "Couchbase Analytics Service",
 "tags": [
  "Couchbase",
  "Couchbase-7",
  "Analytics-Services",
  "Analytics",
  "CBAS"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "15s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" },
   {
    "name": "cluster",
    "label": "Cluster",
    "query": {
     "query": "label_values(cbas_disk_used_bytes_total,cluster_name)"
    }
   },
   {
    "name": "node",
    "label": "Node",
    "query": {
     "query": "label_values(cbas_disk_used_bytes_total{cluster_name=~\"$cluster\"},instance)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Disk Used",
   "type": "timeseries",
   "description": "Total disk used in bytes",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "cbas_disk_used_bytes_total{cluster_name=~\"$cluster\",instance=~\"$node\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Incoming Records/sec by Node",
   "type": "timeseries",
   "description": "Number of the incoming records",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (instance, link) (rate(cbas_incoming_records_count{cluster_name=~\"$cluster\",instance=~\"$node\"}[$__rate_interval]))",
     "legendFormat": "{{link}} - {{instance}}"
    }
   ]
  },
  {
   "title": "Incoming Records/sec by Bucket",
   "type": "timeseries",
   "description": "Number of the incoming records",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (bucket, link) (rate(cbas_incoming_records_count{cluster_name=~\"$cluster\",instance=~\"$node\"}[$__rate_interval]))",
     "legendFormat": "{{link}} - {{bucket}}"
    }
   ]
  },
  {
   "title": "System Load",
   "type": "timeseries",
   "description": "System work load",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "cbas_system_load_average{cluster_name=~\"$cluster\",instance=~\"$node\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Failed to Parse Records by Node",
   "type": "timeseries",
   "description": "Number of the failed to parse records",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (link, instance) (cbas_failed_to_parse_records_count{cluster_name=~\"$cluster\",instance=~\"$node\"})",
     "legendFormat": "{{link}} - {{instance}}"
    }
   ]
  },
  {
   "title": "Failed to Parse Records by Bucket",
   "type": "timeseries",
   "description": "Number of the failed to parse records",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (link, bucket) (cbas_failed_to_parse_records_count{cluster_name=~\"$cluster\",instance=~\"$node\"})",
     "legendFormat": "{{link}} - {{bucket}}"
    }
   ]
  },
  {
   "title": "Direct Memory",
   "type": "timeseries",
   "description": "Direct memory used in bytes",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "cbas_direct_memory_used_bytes{cluster_name=~\"$cluster\",instance=~\"$node\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "IO Reads",
   "type": "timeseries",
   "description": "Total number of IO reads",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(cbas_io_reads_total{cluster_name=~\"$cluster\",instance=~\"$node\"}[$__rate_interval])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "IO Writes",
   "type": "timeseries",
   "description": "Total number of IO writes",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(cbas_io_writes_total{cluster_name=~\"$cluster\",instance=~\"$node\"}[$__rate_interval])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Garbage Collection Time",
   "type": "timeseries",
   "description": "Total time of garbage collections in milliseconds",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(cbas_gc_time_milliseconds_total{cluster_name=~\"$cluster\",instance=~\"$node\"}[$__rate_interval])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Heap Memory",
   "type": "timeseries",
   "description": "Heap memory used in bytes",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "cbas_heap_memory_used_bytes{cluster_name=~\"$cluster\",instance=~\"$node\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Threads",
   "type": "timeseries",
   "description": "Number of threads in use",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "cbas_thread_count{cluster_name=~\"$cluster\",instance=~\"$node\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Pending Flush Ops",
   "type": "timeseries",
   "description": "Total number of pending flush operations",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "cbas_pending_flush_ops{cluster_name=~\"$cluster\",instance=~\"$node\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Pending Merge Ops",
   "type": "timeseries",
   "description": "Total number of pending merge operations",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "cbas_pending_merge_ops{cluster_name=~\"$cluster\",instance=~\"$node\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Memory Pages in Virtual Buffer Cache",
   "type": "timeseries",
   "description": "Total number of used memory pages in the virtual buffer cache",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "cbas_virtual_buffer_cache_used_pages{cluster_name=~\"$cluster\",instance=~\"$node\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Node Resources",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 },
   "collapsed": true,
   "panels": [
    {
     "title": "System Processes",
     "type": "table",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 32 },
     "targets": [
      {
       "expr": "sysproc_cpu_utilization{cluster_name=\"$cluster\",instance=~\"$node\"}"
      },
      {
       "expr": "sysproc_mem_size{cluster_name=\"$cluster\",instance=~\"$node\"}"
      },
      {
       "expr": "sysproc_mem_resident{cluster_name=\"$cluster\",instance=~\"$node\"}"
      },
      {
       "expr": "sysproc_mem_share{cluster_name=\"$cluster\",instance=~\"$node\"}"
      }
     ]
    },
    {
     "title": "CPU Utilization ",
     "type": "timeseries",
     "description": "CPU Utilization per Node.\n\nRequires Node Exporter Metrics (https://github.com/prometheus/node_exporter)",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 41 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "100 - (\n avg(\n    rate(\n      node_cpu_seconds_total{instance=~\"$node\",mode=\"idle\"}[$__rate_interval]\n    )\n  ) by (instance)\n  * 100\n)",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "cbas and java CPU Usage",
     "type": "timeseries",
     "description": "Requires Process Exporter (https://github.com/ncabatoff/process-exporter)",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 41 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "avg(\n    rate(\n      namedprocess_namegroup_cpu_seconds_total{instance=~\"$node\",groupname=~\"(java|cbas).*\",mode=~\"user|system\"}[$__rate_interval]\n    ) \n) by (instance, groupname)",
       "legendFormat": "{{groupname}} - {{instance}}"
      }
     ]
    },
    {
     "title": "Memory Utilization ",
     "type": "timeseries",
     "description": "Memory Utilization  per Node.\n\nRequires Node Exporter Metrics (https://github.com/prometheus/node_exporter)",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 48 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "100 * (\n  1 \n  - \n  (\n    avg(\n      avg_over_time(\n        node_memory_MemFree_bytes{instance=~\"$node\"}[$__rate_interval]\n      ) + \n      avg_over_time(\n        node_memory_Cached_bytes{instance=~\"$node\"}[$__rate_interval]\n      ) + \n      avg_over_time(\n        node_memory_Buffers_bytes{instance=~\"$node\"}[$__rate_interval]\n      )\n    ) by (instance)\n  )\n  / \n  avg(node_memory_MemTotal_bytes{instance=~\"$node\"}\n  ) by (instance)\n)",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "cbas and java Memory Usage",
     "type": "timeseries",
     "description": "Requires Process Exporter (https://github.com/ncabatoff/process-exporter)",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 48 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "avg(\n  avg_over_time(namedprocess_namegroup_memory_bytes{instance=~\"$node\",groupname=~\"(java|cbas).*\",memtype=\"swapped\"}[$__rate_interval])\n  + \n  ignoring (memtype) avg_over_time(namedprocess_namegroup_memory_bytes{instance=~\"$node\",groupname=~\"(java|cbas).*\",memtype=\"resident\"}[$__rate_interval])\n) by (groupname, instance)",
       "legendFormat": "{{groupname}} - {{instance}}"
      }
     ]
    },
    {
     "title": "Disk Operations",
     "type": "timeseries",
     "description": "The number of bytes read from or written to the device per second.\nRequires Node Exporter Metrics (https://github.com/prometheus/node_exporter)",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 55 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "sum(rate(node_disk_written_bytes_total{cluster_name=~\"$cluster\",instance=~\"$node\"}[$__rate_interval])) by (instance)",
       "legendFormat": "Write bytes - {{instance}}"
      },
      {
       "expr": "-sum(rate(node_disk_read_bytes_total{cluster_name=~\"$cluster\",instance=~\"$node\"}[$__rate_interval])) by (instance)",
       "legendFormat": "Read bytes - {{instance}}"
      }
     ]
    },
    {
     "title": "cbas and java Disk Operations",
     "type": "timeseries",
     "description": "Requires Process Exporter (https://github.com/ncabatoff/process-exporter)",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 55 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "-sum(rate(namedprocess_namegroup_read_bytes_total{cluster_name=~\"$cluster\",instance=~\"$node\",groupname=~\"(java|cbas).*\"}[$__rate_interval])) by (groupname, instance)",
       "legendFormat": "{{groupname}} - read - {{instance}}"
      },
      {
       "expr": "sum(rate(namedprocess_namegroup_write_bytes_total{cluster_name=~\"$cluster\",instance=~\"$node\",groupname=~\"(java|cbas).*\"}[$__rate_interval])) by (groupname, instance)",
       "legendFormat": "{{groupname}} - write - {{instance}}"
      }
     ]
    },
    {
     "title": "Network Traffic",
     "type": "timeseries",
     "description": "Basic network info per interface.\nRequires Node Exporter Metrics (https://github.com/prometheus/node_exporter)",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 62 },
     "fieldConfig": { "defaults": { "unit": "bps" } },
     "targets": [
      {
       "expr": "sum(rate(node_network_transmit_bytes_total{instance=~\"$node\"}[$__rate_interval])*8) by (instance)",
       "legendFormat": "{{instance}} - TX"
      },
      {
       "expr": "-sum(rate(node_network_receive_bytes_total{instance=~\"$node\"}[$__rate_interval])*8) by (instance)",
       "legendFormat": "{{instance}} - RX"
      }
     ]
    },
    {
     "title": "cbas and java Open File Descriptors",
     "type": "timeseries",
     "description": "Requires Process Exporter (https://github.com/ncabatoff/process-exporter)",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 62 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "avg(\n  max_over_time(namedprocess_namegroup_open_filedesc{cluster_name=~\"$cluster\",instance=~\"$node\",groupname=~\"(java|cbas).*\"}[$__rate_interval])\n) by (groupname, instance)",
       "legendFormat": "{{groupname}} - {{instance}}"
      }
     ]
    }
   ]
  }
 ]
}