global:
  scrape_interval:     5s
  evaluation_interval: 5s

  external_labels:
     monitor: observability

rule_files:
  - '/etc/prometheus/rules/*.yml'

scrape_configs:
  - job_name: 'server_metrics'
    basic_auth:
      username: "metrics_user"
      password: "password"
    scheme: "https"
    tls_config:
      insecure_skip_verify: true
    http_sd_configs:
      # https://docs.couchbase.com/server/current/rest-api/rest-discovery-api.html
      - url: "http://couchbase:8091/prometheus_sd_config?clusterLabels=uuidAndName"
        refresh_interval: 30s
        basic_auth:
          username: "Administrator"
          password: "password"

  - job_name: 'sgw_metrics'
    metrics_path: /_metrics
    basic_auth:
      username: "metrics_user"
      password: "password"
    static_configs:
      - targets: ["sync-gateway:4986"]

  - job_name: 'node_metrics'
    static_configs:
      - targets: ['node-exporter:9100']
    
