global:
  scrape_interval:     5s
  evaluation_interval: 5s

  external_labels:
     monitor: observability

rule_files:
  - '/etc/prometheus/rules/*.yml'

scrape_configs:
  - job_name: 'server_metrics'
    basic_auth:
      username: "metrics_user"
      password: "password"
    static_configs:
      - targets: [ "couchbase:8091"]

  - job_name: 'sgw_metrics'
    metrics_path: /_metrics
    basic_auth:
      username: "metrics_user"
      password: "password"
    static_configs:
      - targets: ["sync-gateway:4986"]

  - job_name: 'node_metrics'
    static_configs:
      - targets: ['node-exporter:9100']
    
