# datasources.yaml
apiVersion: 1

# list of datasources that should be deleted from the database
deleteDatasources:
  - name: Prometheus
    orgId: 1
    
# list of datasources to insert/update depending
# what's available in the database
datasources:
  - name: Prometheus
    type: prometheus
    orgId: 1
    isDefault: true
    url: http://prometheus:9090
    access: proxy
    # <map> fields that will be converted to json and stored in json_data
    jsonData:
      graphiteVersion: '1.1'
      tlsSkipVerify: true
      tlsAuth: false
      tlsAuthWithCACert: false
  - name: Query Service
    type: yesoreyeram-infinity-datasource
    orgId: 1
    access: "proxy"
    url: "http://couchbase:8093/query/service"
    jsonData:
      allowedHosts:
        - "http://couchbase:8093"
    basicAuth: true
    basicAuthUser: Administrator
    secureJsonData:
      basicAuthPassword: password
#  - name: Loki
#    type: loki
#    access: proxy
#    orgId: 1
#    url: http://loki:3100
#    basicAuth: false
#    isDefault: true
#    version: 1
#    editable: false
