# datasources.yaml
apiVersion: 1
datasources:
  - name: Prometheus
    type: prometheus
    url: http://prometheus:9090
    access: proxy
  # <map> fields that will be converted to json and stored in json_data
    jsonData:
       graphiteVersion: '1.1'
       tlsAuth: false
       tlsAuthWithCACert: false
