{
 "title": "Chronicle Cluster",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "chronicle disk operations taking over 1 second",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum without (op) (cm_chronicle_disk_latency_seconds_bucket{le=\"+Inf\"} - ignoring(le) cm_chronicle_disk_latency_seconds_bucket{le=\"1.0\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "chronicle disk operations per second",
   "type": "timeseries",
   "description": "Number of chronicle disk operations per second by type.\nComputed as: `irate(cm_chronicle_disk_latency_seconds_count[5m])`",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum without (op) (irate(cm_chronicle_disk_latency_seconds_count[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "average chronicle sync latency (ms)",
   "type": "timeseries",
   "description": "Average chronicle fsync latency (i.e. total time waiting for fsyncs\ndivided by the number of fsyncs in the period. Computed as: `1000 * irate(cm_chronicle_disk_latency_seconds_sum{op=\"sync\"}[5m]) /\nignoring(name) irate(cm_chronicle_disk_latency_seconds_count{op=\"sync\"}[5m])`",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "1000 * irate(cm_chronicle_disk_latency_seconds_sum{op=\"sync\"}[5m]) / ignoring(name) irate(cm_chronicle_disk_latency_seconds_count{op=\"sync\"}[5m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "number of chronicle appends / s",
   "type": "timeseries",
   "description": "Number of chronicle appends performed per second. Computed as:\n`irate(cm_chronicle_append_num_total[5m])`",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(cm_chronicle_append_num_total[5m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "maximum number of appends batched at the storage over 1 minute",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "cm_chronicle_append_batch_size_1m_max",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}