{
 "title": "Cluster Overview",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "sys_cpu_utilization_rate",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "sys_cpu_utilization_rate", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "sys_mem_limit and used",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "sys_mem_limit", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "sys_mem_free",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "sys_mem_free", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "total kv_ops",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "irate(kv_ops[5m])", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "kv gets and mutations",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(kv_ops{op=\"get\"}[5m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "kv_mem_used_bytes",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "kv_mem_used_bytes", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "irate(n1ql_requests[1m])",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "irate(n1ql_requests[5m])", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "n1ql selects, updates & inserts",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "irate(n1ql_selects[5m])", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "index items",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "index_items_count", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "index scans / second",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(index_num_rows_scanned[5m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "index_memory_used",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 60 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "index_memory_used", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Disk usage over buckets",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 60 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "couch_docs_actual_disk_size", "legendFormat": "__auto" }
   ]
  }
 ]
}