{
 "title": "KV View - Node & Bucket",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "node", "query": "prometheus" },
   {
    "name": "bucket",
    "query": {
     "query": "label_values(kv_bg_wait_seconds_bucket,bucket)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Collections",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Memory Used by Collection",
   "type": "timeseries",
   "description": "Memory used per collection in bytes\n\nkv_collection_mem_used_bytes",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kv_collection_mem_used_bytes{bucket=\"$bucket\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Operations Run on Collection",
   "type": "timeseries",
   "description": "Operations run on a particular collection\n\nkv_collection_ops",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kv_collection_ops{bucket=\"$bucket\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Connections",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Connections Ever Opened",
   "type": "timeseries",
   "description": "Connections that have ever been opened\n\nkv_total_connections",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "kv_total_connections", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Current Connections",
   "type": "timeseries",
   "description": "kv_curr_connections, kv_daemon_connections, kv_system_connections, Total Connections",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "kv_curr_connections", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Number of Auth Errors",
   "type": "timeseries",
   "description": "Number of auth errors\n\nkv_auth_errors",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kv_auth_errors{bucket=\"$bucket\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "DCP",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 38 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Backoff Events",
   "type": "timeseries",
   "description": "Total number of backoff events\n\nkv_dcp_backoff",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kv_dcp_backoff{bucket=\"$bucket\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Idle Timeout",
   "type": "timeseries",
   "description": "DCP idle timeout value\n\nkv_ep_dcp_idle_timeout",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kv_ep_dcp_idle_timeout{bucket=\"$bucket\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Producer Count",
   "type": "timeseries",
   "description": "Number of DCP Producers\n\nkv_dcp_producer_count",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kv_dcp_producer_count{bucket=\"$bucket\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Remaining Items",
   "type": "timeseries",
   "description": "Total items remaining to be sent\n\nkv_dcp_items_remaining",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kv_dcp_items_remaining{bucket=\"$bucket\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Sent Items",
   "type": "timeseries",
   "description": "Total items sent\n\nkv_dcp_items_sent",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 63 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(kv_dcp_items_sent{bucket=\"$bucket\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Connections",
   "type": "timeseries",
   "description": "Connection count\n\nkv_dcp_connection_count",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 63 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kv_dcp_connection_count{bucket=\"$bucket\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Data Size",
   "type": "timeseries",
   "description": "kv_dcp_total_data_size_bytes, kv_dcp_total_uncompressed_data_size_bytes",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 75 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kv_dcp_total_data_size_bytes{bucket=\"$bucket\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Data",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 87 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Data Operation Failures",
   "type": "timeseries",
   "description": "kv_ep_data_read_failed, kv_ep_data_write_failed",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 88 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kv_ep_data_read_failed{bucket=\"$bucket\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Doc Size",
   "type": "timeseries",
   "description": "couch_docs_actual_disk_size",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 88 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "couch_docs_actual_disk_size{bucket=\"$bucket\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Number of Docs",
   "type": "timeseries",
   "description": "kv_curr_items, kv_curr_items_tot",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 100 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kv_curr_items{bucket=\"$bucket\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Percentage Memory Resident",
   "type": "timeseries",
   "description": "kv_vb_perc_mem_resident_ratio",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 100 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kv_vb_perc_mem_resident_ratio{state=\"active\", bucket=\"$bucket\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Rate of Deletes",
   "type": "timeseries",
   "description": "The number of deleted documents, converted into tombstones, every minute\n\nkv_ep_total_del_items",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 112 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(kv_ep_total_del_items{bucket=\"$bucket\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Rate of Doc Expirations",
   "type": "timeseries",
   "description": "kv_vb_expired",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 112 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(kv_vb_expired{state=\"active\", bucket=\"$bucket\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Rollback Item Count",
   "type": "timeseries",
   "description": "kv_rollback_item_count",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 124 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kv_rollback_item_count{bucket=\"$bucket\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Size of Key",
   "type": "stat",
   "description": "Minimum key count that bloom filter will accomodate\n\nkv_ep_bfilter_key_count",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 124 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kv_ep_bfilter_key_count{bucket=\"$bucket\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Disk",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 136 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Data Size",
   "type": "timeseries",
   "description": "couch_docs_actual_disk_size",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 137 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "couch_docs_actual_disk_size{bucket=\"$bucket\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Disk Queue Items",
   "type": "timeseries",
   "description": "Total number of items in disk queue\n\nkv_ep_diskqueue_items",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 137 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kv_ep_diskqueue_items{bucket=\"$bucket\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Disk Queue Memory Usage",
   "type": "timeseries",
   "description": "Total memory used by disk queue, in bytes\n\nkv_ep_diskqueue_memory_bytes",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 149 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kv_ep_diskqueue_memory_bytes{bucket=\"$bucket\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "New and Persisted Items",
   "type": "timeseries",
   "description": "kv_ep_total_new_items, kv_ep_total_persisted",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 149 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kv_ep_total_new_items{bucket=\"$bucket\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Written / Read Bytes",
   "type": "timeseries",
   "description": "kv_written_bytes, kv_read_bytes",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 161 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kv_written_bytes{bucket=\"$bucket\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "General",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 173 },
   "targets": [
    {}
   ]
  },
  {
   "title": "KV CPU Utilization",
   "type": "timeseries",
   "description": "KV service CPU Utilization of all cores summed up, in percent\n\nsysproc_cpu_utilization{proc=\"memcached\"}",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 174 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sysproc_cpu_utilization{proc=\"memcached\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Failed KV Operations",
   "type": "timeseries",
   "description": "Number of failed KV operations\n\nkv_ops_failed",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 174 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kv_ops_failed{bucket=\"$bucket\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "KV Operations",
   "type": "timeseries",
   "description": "kv_ops",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 186 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(kv_ops{bucket=\"$bucket\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "KV Uptime",
   "type": "timeseries",
   "description": "KV service uptime in seconds\n\nkv_uptime_seconds",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 186 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "kv_uptime_seconds", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "KV Memory Usage",
   "type": "timeseries",
   "description": "Memory usage by the KV service, in bytes\n\nkv_mem_used_bytes, kv_ep_mem_high_wat, kv_ep_mem_low_wat",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 198 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kv_ep_mem_high_wat{bucket=\"$bucket\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 210 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Checkpoint Memory",
   "type": "timeseries",
   "description": "kv_ep_checkpoint_memory_overhead_bytes, kv_ep_checkpoint_memory_unreferenced_bytes",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 211 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kv_ep_checkpoint_memory_overhead_bytes{bucket=\"$bucket\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Checkpoint Memory Size",
   "type": "timeseries",
   "description": "Memory of items in all checkpoints, in bytes\n\nkv_ep_checkpoint_memory_bytes",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 211 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kv_ep_checkpoint_memory_bytes{bucket=\"$bucket\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Defragmenter Enabled",
   "type": "bargauge",
   "description": "Whether the defragmenter is enabled or not\n\nkv_ep_defragmenter_enabled",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 223 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kv_ep_defragmenter_enabled{bucket=\"$bucket\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Defragmenter Interval",
   "type": "stat",
   "description": "How often defragmenter task should run, in seconds\n\nkv_ep_defragmenter_interval",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 223 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kv_ep_defragmenter_interval{bucket=\"$bucket\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "KV Memory Usage",
   "type": "timeseries",
   "description": "Memory usage by the KV service, in bytes\n\nkv_mem_used_bytes, kv_ep_mem_high_wat, kv_ep_mem_low_wat",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 235 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kv_ep_mem_high_wat{bucket=\"$bucket\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Metadata Overhead",
   "type": "timeseries",
   "description": "kv_vb_meta_data_memory_bytes",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 235 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kv_vb_meta_data_memory_bytes{state=\"active\", bucket=\"$bucket\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "OOM Errors",
   "type": "timeseries",
   "description": "kv_ep_oom_errors, kv_ep_warmup_oom",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 247 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kv_ep_oom_errors{bucket=\"$bucket\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "vBuckets",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 259 },
   "targets": [
    {}
   ]
  },
  {
   "title": "vBucket Operations (Active)",
   "type": "timeseries",
   "description": "kv_vb_ops_create, kv_vb_ops_delete, kv_vb_ops_reject, kv_vb_ops_update, kv_vb_ops_get",
   "gridPos": { "h": 12, "w": 8, "x": 0, "y": 260 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(kv_vb_ops_create{state=\"active\", bucket=\"$bucket\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "vBucket Operations (Replica)",
   "type": "timeseries",
   "description": "kv_vb_ops_create, kv_vb_ops_delete, kv_vb_ops_reject, kv_vb_ops_update, kv_vb_ops_get",
   "gridPos": { "h": 12, "w": 8, "x": 8, "y": 260 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(kv_vb_ops_create{state=\"replica\", bucket=\"$bucket\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "vBucket Operations (Pending)",
   "type": "timeseries",
   "description": "kv_vb_ops_create, kv_vb_ops_delete, kv_vb_ops_reject, kv_vb_ops_update, kv_vb_ops_get",
   "gridPos": { "h": 12, "w": 8, "x": 16, "y": 260 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(kv_vb_ops_create{state=\"pending\", bucket=\"$bucket\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total",
   "type": "timeseries",
   "description": "kv_num_vbuckets",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 272 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kv_num_vbuckets{bucket=\"$bucket\",state=\"active\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}