{
 "title": "KV View - Cluster",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "General",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "KV CPU Utilization",
   "type": "timeseries",
   "description": "KV service CPU Utilization of all cores summed up, in percent\n\nsysproc_cpu_utilization{proc=\"memcached\"}",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sysproc_cpu_utilization{proc=\"memcached\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "KV Uptime",
   "type": "timeseries",
   "description": "KV service uptime in seconds\n\nkv_uptime_seconds",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "kv_uptime_seconds", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "KV Memory Usage",
   "type": "timeseries",
   "description": "Memory usage by the KV service, in bytes\n\nsysproc_mem_resident{proc=\"memcached\"}",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sysproc_mem_resident{proc=\"memcached\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Disk Usage",
   "type": "timeseries",
   "description": "couch_docs_actual_disk_size",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(couch_docs_actual_disk_size)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Ops",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Total kv_ops",
   "type": "timeseries",
   "description": "For each node, computed as:\n`sum(irate(kv_ops[1m]))`",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "sum(irate(kv_ops[1m]))", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "KV Gets and Mutations",
   "type": "timeseries",
   "description": "Gets computed as: `sum(irate(kv_ops{op=\"get\"}[1m]))`\nMutations computed as:`sum(irate(kv_ops{op=~\"set|set_meta|set_ret_meta|cas|decr|del_meta|del_ret_meta|incr|delete\"}[1m]))`",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(irate(kv_ops{op=\"get\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total BG Fetches",
   "type": "timeseries",
   "description": "For each node computed as:\n`sum(irate(kv_ep_bg_fetched[5m]))`",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(irate(kv_ep_bg_fetched[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Percentile GET or GAT latencies",
   "type": "timeseries",
   "description": "For each node computed as:\n`histogram_quantile(0.90, sum by (le) (irate(kv_cmd_duration_seconds_bucket{opcode=~\"GET|GAT\"}[10m])))`",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by (le) (irate(kv_cmd_duration_seconds_bucket{opcode=~\"GET|GAT\"}[10m])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Connections",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 50 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Accumulated Connections",
   "type": "timeseries",
   "description": "Number of KV service connections accumulated over time\n\nkv_total_connections",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "kv_total_connections", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Current Connections",
   "type": "timeseries",
   "description": "Number of KV service connections currently open\n\nkv_curr_connections, kv_daemon_connections, kv_system_connections",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(kv_curr_connections) + sum(kv_daemon_connections) + sum(kv_system_connections)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Audit Daemon",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 63 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Audit Daemon Enabled",
   "type": "bargauge",
   "description": "Whether the audit daemon is enabled\n\nkv_audit_enabled",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 64 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "kv_audit_enabled", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Dropped Events",
   "type": "timeseries",
   "description": "kv_audit_dropped_events",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 64 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "kv_audit_dropped_events", "legendFormat": "__auto" }
   ]
  }
 ]
}