{
 "title": "KV View - Node",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "node", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "Ops",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Total kv_ops by bucket",
   "type": "timeseries",
   "description": "Computed as:\n`sum by (bucket) (irate(kv_ops[5m]))`",
   "gridPos": { "h": 12, "w": 8, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (bucket) (irate(kv_ops[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "KV Gets by Bucket",
   "type": "timeseries",
   "description": "Computed as: `sum by (bucket) (irate(kv_ops{op=\"get\"}[5m]))`",
   "gridPos": { "h": 12, "w": 8, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (bucket) (irate(kv_ops{op=\"get\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "KV Mutations by Bucket",
   "type": "timeseries",
   "description": "Computed as:`sum by (bucket) (irate(kv_ops{op=~\"set|set_meta|set_ret_meta|cas|decr|del_meta|del_ret_meta|incr|delete\"}[5m]))`",
   "gridPos": { "h": 12, "w": 8, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (bucket) (irate(kv_ops{op=~\"set|set_meta|set_ret_meta|cas|decr|del_meta|del_ret_meta|incr|delete\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total BG Fetches",
   "type": "timeseries",
   "description": "For each node computed as:\n`sum(irate(kv_ep_bg_fetched[5m]))`",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(irate(kv_ep_bg_fetched[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Percentile GET or GAT latencies",
   "type": "timeseries",
   "description": "For each node computed as:\n`histogram_quantile(0.90, sum by (le) (irate(kv_cmd_duration_seconds_bucket{opcode=~\"GET|GAT\"}[10m])))`",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.90, sum by (le) (irate(kv_cmd_duration_seconds_bucket{opcode=~\"GET|GAT\"}[10m])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Top Non-DCP Opcodes",
   "type": "timeseries",
   "description": "For each node computed as:\n`topk(5, sum by (opcode) (kv_cmd_duration_seconds_count))`",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "topk(5, sum by (opcode) (kv_cmd_duration_seconds_count{opcode!~\"DCP.*\"}))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Data",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 37 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Data Read Failures",
   "type": "timeseries",
   "description": "kv_ep_data_read_failed",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "kv_ep_data_read_failed", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Data Write Failures",
   "type": "timeseries",
   "description": "kv_ep_data_write_failed",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "kv_ep_data_write_failed", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Doc Size",
   "type": "timeseries",
   "description": "couch_docs_actual_disk_size",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "couch_docs_actual_disk_size", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Number of Docs (inc. Replicas)",
   "type": "timeseries",
   "description": "kv_curr_items_tot",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "kv_curr_items_tot", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Percentage Memory Resident",
   "type": "timeseries",
   "description": "kv_vb_perc_mem_resident_ratio",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 62 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "kv_vb_perc_mem_resident_ratio", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Compaction write & read bytes",
   "type": "timeseries",
   "description": "irate(kv_ep_io_compaction_write_bytes_bytes[5m]) and irate(kv_ep_io_compaction_read_bytes_bytes[5m])",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 62 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(kv_ep_io_compaction_write_bytes_bytes[5m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Rate of Deletes",
   "type": "timeseries",
   "description": "The number of deleted documents, converted into tombstones, every minute\n\nkv_ep_total_del_items",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 74 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(kv_ep_total_del_items[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Rate of Doc Expirations",
   "type": "timeseries",
   "description": "kv_vb_expired",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 74 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(kv_vb_expired[1m])) by (bucket)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Rollback Item Count",
   "type": "timeseries",
   "description": "kv_rollback_item_count",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 86 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "kv_rollback_item_count", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Size of Key",
   "type": "stat",
   "description": "Minimum key count that bloom filter will accomodate\n\nkv_ep_bfilter_key_count",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 86 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "kv_ep_bfilter_key_count", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Disk",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 98 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Data Size",
   "type": "timeseries",
   "description": "couch_docs_actual_disk_size",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 99 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "couch_docs_actual_disk_size", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Disk Queue Items",
   "type": "timeseries",
   "description": "Total number of items in disk queue\n\nkv_ep_diskqueue_items",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 99 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "kv_ep_diskqueue_items", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Disk Queue Memory Usage",
   "type": "timeseries",
   "description": "Total memory used by disk queue, in bytes\n\nkv_ep_diskqueue_memory_bytes",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 111 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "kv_ep_diskqueue_memory_bytes", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "New and Persisted Items",
   "type": "timeseries",
   "description": "kv_ep_total_new_items, kv_ep_total_persisted",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 111 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(kv_ep_total_new_items) by (bucket) + sum(kv_ep_total_persisted) by (bucket)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Written Bytes",
   "type": "timeseries",
   "description": "kv_written_bytes",
   "gridPos": { "h": 12, "w": 6, "x": 0, "y": 123 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "kv_written_bytes", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Read Bytes",
   "type": "timeseries",
   "description": "kv_read_bytes",
   "gridPos": { "h": 12, "w": 6, "x": 6, "y": 123 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "kv_read_bytes", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "General",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 135 },
   "targets": [
    {}
   ]
  },
  {
   "title": "KV CPU Utilization",
   "type": "timeseries",
   "description": "KV service CPU Utilization of all cores summed up, in percent\n\nsysproc_cpu_utilization{proc=\"memcached\"}",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 136 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sysproc_cpu_utilization{proc=\"memcached\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Failed KV Operations",
   "type": "timeseries",
   "description": "Number of failed KV operations\n\nkv_ops_failed",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 136 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "sum(kv_ops_failed) by (bucket)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "KV Operations",
   "type": "timeseries",
   "description": "kv_ops",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 148 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(kv_ops[1m])) by (bucket)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "KV Uptime",
   "type": "timeseries",
   "description": "KV service uptime in seconds\n\nkv_uptime_seconds",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 148 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "kv_uptime_seconds", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "KV Memory Usage",
   "type": "timeseries",
   "description": "Memory usage by the KV service, in bytes\n\nsysproc_mem_resident{proc=\"memcached\"}",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 160 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sysproc_mem_resident{proc=\"memcached\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 172 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Checkpoint Memory Size",
   "type": "timeseries",
   "description": "Memory of items in all checkpoints, in bytes\n\nkv_ep_checkpoint_memory_bytes",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 173 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "kv_ep_checkpoint_memory_bytes", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Defragmenter Enabled",
   "type": "bargauge",
   "description": "Whether the defragmenter is enabled or not\n\nkv_ep_defragmenter_enabled",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 173 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "kv_ep_defragmenter_enabled", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Defragmenter Interval",
   "type": "gauge",
   "description": "How often defragmenter task should run, in seconds\n\nkv_ep_defragmenter_interval",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 185 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "kv_ep_defragmenter_interval", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "KV Memory Usage",
   "type": "timeseries",
   "description": "Memory usage by the KV service, in bytes\n\nsysproc_mem_resident{proc=\"memcached\"}",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 185 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sysproc_mem_resident{proc=\"memcached\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Metadata Overhead",
   "type": "timeseries",
   "description": "kv_vb_meta_data_memory_bytes",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 197 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(kv_vb_meta_data_memory_bytes) by (bucket)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "OOM Errors Total",
   "type": "timeseries",
   "description": "kv_ep_oom_errors",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 197 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "kv_ep_oom_errors", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "OOM Errors at Warmup",
   "type": "timeseries",
   "description": "kv_ep_warmup_oop",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 209 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "kv_ep_warmup_oom", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "DCP",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 221 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Backoff Events",
   "type": "timeseries",
   "description": "Total number of backoff events\n\nkv_dcp_backoff",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 222 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "kv_dcp_backoff", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Idle Timeout",
   "type": "gauge",
   "description": "DCP idle timeout value\n\nkv_ep_dcp_idle_timeout",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 222 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "kv_ep_dcp_idle_timeout", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Producer Count",
   "type": "timeseries",
   "description": "Number of DCP Producers\n\nkv_dcp_producer_count",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 234 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "kv_dcp_producer_count", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Remaining Items",
   "type": "timeseries",
   "description": "Total items remaining to be sent\n\nkv_dcp_items_remaining",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 234 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "kv_dcp_items_remaining", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Sent Items",
   "type": "timeseries",
   "description": "Total items sent\n\nkv_dcp_items_sent",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 246 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "rate(kv_dcp_items_sent[1m])", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Total Connections",
   "type": "timeseries",
   "description": "Connection count\n\nkv_dcp_connection_count",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 246 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "kv_dcp_connection_count", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Total Data Size",
   "type": "timeseries",
   "description": "kv_dcp_total_data_size_bytes",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 258 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "kv_dcp_total_data_size_bytes", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "vBuckets",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 270 },
   "targets": [
    {}
   ]
  },
  {
   "title": "vBucket Operations (Active)",
   "type": "timeseries",
   "description": "kv_vb_ops_create, kv_vb_ops_delete, kv_vb_ops_reject, kv_vb_ops_update, kv_vb_ops_get",
   "gridPos": { "h": 12, "w": 8, "x": 0, "y": 271 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(kv_vb_ops_create{state=\"active\"}[1m])) by (bucket) + sum(rate(kv_vb_ops_delete{state=\"active\"}[1m])) by (bucket) + sum(rate(kv_vb_ops_reject{state=\"active\"}[1m])) by (bucket) + sum(rate(kv_vb_ops_update{state=\"active\"}[1m])) by (bucket) + sum(rate(kv_vb_ops_get{state=\"active\"}[1m])) by (bucket)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "vBucket Operations (Replica)",
   "type": "timeseries",
   "description": "kv_vb_ops_create, kv_vb_ops_delete, kv_vb_ops_reject, kv_vb_ops_update, kv_vb_ops_get",
   "gridPos": { "h": 12, "w": 8, "x": 8, "y": 271 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(kv_vb_ops_create{state=\"replica\"}[1m])) by (bucket) + sum(rate(kv_vb_ops_delete{state=\"replica\"}[1m])) by (bucket) + sum(rate(kv_vb_ops_reject{state=\"replica\"}[1m])) by (bucket) + sum(rate(kv_vb_ops_update{state=\"replica\"}[1m])) by (bucket) + sum(rate(kv_vb_ops_get{state=\"replica\"}[1m])) by (bucket)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "vBucket Operations (Pending)",
   "type": "timeseries",
   "description": "kv_vb_ops_create, kv_vb_ops_delete, kv_vb_ops_reject, kv_vb_ops_update, kv_vb_ops_get",
   "gridPos": { "h": 12, "w": 8, "x": 16, "y": 271 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(kv_vb_ops_create{state=\"pending\"}[1m])) by (bucket) + sum(rate(kv_vb_ops_delete{state=\"pending\"}[1m])) by (bucket) + sum(rate(kv_vb_ops_reject{state=\"pending\"}[1m])) by (bucket) + sum(rate(kv_vb_ops_update{state=\"pending\"}[1m])) by (bucket) + sum(rate(kv_vb_ops_get{state=\"pending\"}[1m])) by (bucket)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total",
   "type": "timeseries",
   "description": "kv_num_vbuckets",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 283 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(kv_num_vbuckets{state=\"active\"}) by (bucket) + sum(kv_num_vbuckets{state=\"replica\"}) by (bucket) + sum(kv_num_vbuckets{state=\"pending\"}) by (bucket)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Collections",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 295 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Memory Used by Collection",
   "type": "timeseries",
   "description": "Memory used per collection in bytes\n\nkv_collection_mem_used_bytes",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 296 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(kv_collection_mem_used_bytes) by (collection)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Operations Run on Collection",
   "type": "timeseries",
   "description": "Operations run on a particular collection\n\nkv_collection_ops",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 296 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(kv_collection_ops) by (collection)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Connections",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 308 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Connections Ever Opened",
   "type": "timeseries",
   "description": "Connections that have ever been opened\n\nkv_total_connections",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 309 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "kv_total_connections", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Current Connections",
   "type": "timeseries",
   "description": "kv_curr_connections, kv_daemon_connections, kv_system_connections, Total Connections",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 309 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "kv_curr_connections", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Number of Auth Errors",
   "type": "timeseries",
   "description": "Number of auth errors\n\nkv_auth_errors",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 321 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "kv_auth_errors", "legendFormat": "__auto" }
   ]
  }
 ]
}