{
 "title": "Search Dashboard",
 "time": { "from": "2023-11-20T00:00:00.000Z", "to": "2023-11-27T00:00:00.000Z" },
 "refresh": "5s",
 "panels": [
  {
   "title": "fts_num_bytes_used_ram",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "fts_num_bytes_used_ram",
     "legendFormat": "xrdclpdbscis02a.unix.medcity.net fts_num_bytes_used_ram"
    },
    {
     "expr": "fts_num_bytes_used_ram",
     "legendFormat": "xrdclpdbscis02b.unix.medcity.net fts_num_bytes_used_ram"
    },
    {
     "expr": "fts_num_bytes_used_ram",
     "legendFormat": "xrdclpdbscis02c.unix.medcity.net fts_num_bytes_used_ram"
    },
    {
     "expr": "fts_num_bytes_used_ram",
     "legendFormat": "xrdclpdbscis02d.unix.medcity.net fts_num_bytes_used_ram"
    },
    {
     "expr": "fts_num_bytes_used_ram",
     "legendFormat": "xrdclpdbscis02e.unix.medcity.net fts_num_bytes_used_ram"
    }
   ]
  },
  {
   "title": "fts_curr_batches_blocked_by_herder",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "fts_curr_batches_blocked_by_herder",
     "legendFormat": "xrdclpdbscis02a.unix.medcity.net fts_curr_batches_blocked_by_herder"
    },
    {
     "expr": "fts_curr_batches_blocked_by_herder",
     "legendFormat": "xrdclpdbscis02b.unix.medcity.net fts_curr_batches_blocked_by_herder"
    },
    {
     "expr": "fts_curr_batches_blocked_by_herder",
     "legendFormat": "xrdclpdbscis02c.unix.medcity.net fts_curr_batches_blocked_by_herder"
    },
    {
     "expr": "fts_curr_batches_blocked_by_herder",
     "legendFormat": "xrdclpdbscis02d.unix.medcity.net fts_curr_batches_blocked_by_herder"
    },
    {
     "expr": "fts_curr_batches_blocked_by_herder",
     "legendFormat": "xrdclpdbscis02e.unix.medcity.net fts_curr_batches_blocked_by_herder"
    }
   ]
  },
  {
   "title": "fts_tot_queryreject_on_memquota",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "fts_tot_queryreject_on_memquota",
     "legendFormat": "xrdclpdbscis02a.unix.medcity.net fts_tot_queryreject_on_memquota"
    },
    {
     "expr": "fts_tot_queryreject_on_memquota",
     "legendFormat": "xrdclpdbscis02b.unix.medcity.net fts_tot_queryreject_on_memquota"
    },
    {
     "expr": "fts_tot_queryreject_on_memquota",
     "legendFormat": "xrdclpdbscis02c.unix.medcity.net fts_tot_queryreject_on_memquota"
    },
    {
     "expr": "fts_tot_queryreject_on_memquota",
     "legendFormat": "xrdclpdbscis02d.unix.medcity.net fts_tot_queryreject_on_memquota"
    },
    {
     "expr": "fts_tot_queryreject_on_memquota",
     "legendFormat": "xrdclpdbscis02e.unix.medcity.net fts_tot_queryreject_on_memquota"
    }
   ]
  },
  {
   "title": "fts_tot_grpc_queryreject_on_memquota",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "fts_tot_grpc_queryreject_on_memquota",
     "legendFormat": "xrdclpdbscis02a.unix.medcity.net fts_tot_grpc_queryreject_on_memquota"
    },
    {
     "expr": "fts_tot_grpc_queryreject_on_memquota",
     "legendFormat": "xrdclpdbscis02b.unix.medcity.net fts_tot_grpc_queryreject_on_memquota"
    },
    {
     "expr": "fts_tot_grpc_queryreject_on_memquota",
     "legendFormat": "xrdclpdbscis02c.unix.medcity.net fts_tot_grpc_queryreject_on_memquota"
    },
    {
     "expr": "fts_tot_grpc_queryreject_on_memquota",
     "legendFormat": "xrdclpdbscis02d.unix.medcity.net fts_tot_grpc_queryreject_on_memquota"
    },
    {
     "expr": "fts_tot_grpc_queryreject_on_memquota",
     "legendFormat": "xrdclpdbscis02e.unix.medcity.net fts_tot_grpc_queryreject_on_memquota"
    }
   ]
  },
  {
   "title": "fts_total_queries_rejected_by_herder",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "fts_total_queries_rejected_by_herder",
     "legendFormat": "xrdclpdbscis02a.unix.medcity.net fts_total_queries_rejected_by_herder"
    },
    {
     "expr": "fts_total_queries_rejected_by_herder",
     "legendFormat": "xrdclpdbscis02b.unix.medcity.net fts_total_queries_rejected_by_herder"
    },
    {
     "expr": "fts_total_queries_rejected_by_herder",
     "legendFormat": "xrdclpdbscis02c.unix.medcity.net fts_total_queries_rejected_by_herder"
    },
    {
     "expr": "fts_total_queries_rejected_by_herder",
     "legendFormat": "xrdclpdbscis02d.unix.medcity.net fts_total_queries_rejected_by_herder"
    },
    {
     "expr": "fts_total_queries_rejected_by_herder",
     "legendFormat": "xrdclpdbscis02e.unix.medcity.net fts_total_queries_rejected_by_herder"
    }
   ]
  },
  {
   "title": "fts_batch_bytes_added",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "fts_batch_bytes_added",
     "legendFormat": "xrdclpdbscis02a.unix.medcity.net fts_batch_bytes_added"
    },
    {
     "expr": "fts_batch_bytes_added",
     "legendFormat": "xrdclpdbscis02b.unix.medcity.net fts_batch_bytes_added"
    },
    {
     "expr": "fts_batch_bytes_added",
     "legendFormat": "xrdclpdbscis02c.unix.medcity.net fts_batch_bytes_added"
    },
    {
     "expr": "fts_batch_bytes_added",
     "legendFormat": "xrdclpdbscis02d.unix.medcity.net fts_batch_bytes_added"
    },
    {
     "expr": "fts_batch_bytes_added",
     "legendFormat": "xrdclpdbscis02e.unix.medcity.net fts_batch_bytes_added"
    }
   ]
  },
  {
   "title": "fts_batch_bytes_removed",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "fts_batch_bytes_removed",
     "legendFormat": "xrdclpdbscis02a.unix.medcity.net fts_batch_bytes_removed"
    },
    {
     "expr": "fts_batch_bytes_removed",
     "legendFormat": "xrdclpdbscis02b.unix.medcity.net fts_batch_bytes_removed"
    },
    {
     "expr": "fts_batch_bytes_removed",
     "legendFormat": "xrdclpdbscis02c.unix.medcity.net fts_batch_bytes_removed"
    },
    {
     "expr": "fts_batch_bytes_removed",
     "legendFormat": "xrdclpdbscis02d.unix.medcity.net fts_batch_bytes_removed"
    },
    {
     "expr": "fts_batch_bytes_removed",
     "legendFormat": "xrdclpdbscis02e.unix.medcity.net fts_batch_bytes_removed"
    }
   ]
  },
  {
   "title": "fts_pct_cpu_gc",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "fts_pct_cpu_gc",
     "legendFormat": "xrdclpdbscis02a.unix.medcity.net fts_pct_cpu_gc"
    },
    {
     "expr": "fts_pct_cpu_gc",
     "legendFormat": "xrdclpdbscis02b.unix.medcity.net fts_pct_cpu_gc"
    },
    {
     "expr": "fts_pct_cpu_gc",
     "legendFormat": "xrdclpdbscis02c.unix.medcity.net fts_pct_cpu_gc"
    },
    {
     "expr": "fts_pct_cpu_gc",
     "legendFormat": "xrdclpdbscis02d.unix.medcity.net fts_pct_cpu_gc"
    },
    {
     "expr": "fts_pct_cpu_gc",
     "legendFormat": "xrdclpdbscis02e.unix.medcity.net fts_pct_cpu_gc"
    }
   ]
  },
  {
   "title": "fts_total_gc",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "fts_total_gc",
     "legendFormat": "xrdclpdbscis02a.unix.medcity.net fts_total_gc"
    },
    {
     "expr": "fts_total_gc",
     "legendFormat": "xrdclpdbscis02b.unix.medcity.net fts_total_gc"
    },
    {
     "expr": "fts_total_gc",
     "legendFormat": "xrdclpdbscis02c.unix.medcity.net fts_total_gc"
    },
    {
     "expr": "fts_total_gc",
     "legendFormat": "xrdclpdbscis02d.unix.medcity.net fts_total_gc"
    },
    {
     "expr": "fts_total_gc",
     "legendFormat": "xrdclpdbscis02e.unix.medcity.net fts_total_gc"
    }
   ]
  }
 ]
}