{
 "title": "Couchbase DCP Overview",
 "tags": [
  "Couchbase",
  "Data",
  "Buckets",
  "DCP"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "15s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" },
   {
    "name": "cluster",
    "label": "Cluster",
    "query": {
     "query": "label_values(kv_auth_cmds, cluster_name)"
    }
   },
   {
    "name": "bucket",
    "label": "Bucket",
    "query": {
     "query": "label_values(kv_num_vbuckets{cluster_name=~\"$cluster\"}, bucket)"
    }
   },
   {
    "name": "opcode",
    "label": "OP",
    "query": {
     "query": "label_values(kv_cmd_duration_seconds_bucket{cluster_name=~\"$cluster\",bucket=~\"$bucket\",opcode=~\"DCP.*\"}, opcode)"
    }
   },
   {
    "name": "node",
    "label": "Node",
    "query": {
     "query": "label_values(kv_auth_cmds{cluster_name=~\"$cluster\",bucket=~\"$bucket\"}, instance)"
    }
   }
  ]
 },
 "panels": [
  { "title": "DCP", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "DCP Backoffs by Connection Type",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum without (instance, bucket) (kv_dcp_backoff{cluster_name=~\"$cluster\",bucket=~\"$bucket\"})",
     "legendFormat": "{{connection_type}}"
    }
   ]
  },
  {
   "title": "DCP Backoffs by Bucket",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum without (instance, connection_type) (kv_dcp_backoff{cluster_name=~\"$cluster\",bucket=~\"$bucket\"})",
     "legendFormat": "{{bucket}}"
    }
   ]
  },
  {
   "title": "DCP Backoffs by Node",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum without (bucket, connection_type) (kv_dcp_backoff{cluster_name=~\"$cluster\",bucket=~\"$bucket\"})",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "DCP Connection Counts by Connection Type",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum without (instance, bucket) (kv_dcp_connection_count{cluster_name=~\"$cluster\",bucket=~\"$bucket\"})",
     "legendFormat": "{{connection_type}}"
    }
   ]
  },
  {
   "title": "DCP Connection Count by Bucket",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum without (instance, connection_type) (kv_dcp_connection_count{cluster_name=~\"$cluster\",bucket=~\"$bucket\"})",
     "legendFormat": "{{bucket}}"
    }
   ]
  },
  {
   "title": "DCP Connection Count by Node",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum without (bucket, connection_type) (kv_dcp_connection_count{cluster_name=~\"$cluster\",bucket=~\"$bucket\"})",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "DCP Items Remaining by Connection Type",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum without (instance, bucket) (kv_dcp_items_remaining{cluster_name=~\"$cluster\",bucket=~\"$bucket\",connection_type=~\".+\"})",
     "legendFormat": "{{connection_type}}"
    }
   ]
  },
  {
   "title": "DCP Items Remaining by Bucket",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum without (instance, connection_type) (kv_dcp_items_remaining{cluster_name=~\"$cluster\",bucket=~\"$bucket\",connection_type=~\".+\"})",
     "legendFormat": "{{bucket}}"
    }
   ]
  },
  {
   "title": "DCP Items Remaining by Node",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum without (bucket, connection_type) (kv_dcp_items_remaining{cluster_name=~\"$cluster\",bucket=~\"$bucket\",connection_type=~\".+\"})",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "DCP Items Sent/sec by Connection Type",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum without (instance, bucket) (rate(kv_dcp_items_sent{cluster_name=~\"$cluster\",bucket=~\"$bucket\",connection_type=~\".+\"}[$__rate_interval]))",
     "legendFormat": "{{connection_type}}"
    }
   ]
  },
  {
   "title": "DCP Items Sent/sec by Bucket",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum without (instance, connection_type) (rate(kv_dcp_items_sent{cluster_name=~\"$cluster\",bucket=~\"$bucket\",connection_type=~\".+\"}[$__rate_interval]))",
     "legendFormat": "{{bucket}}"
    }
   ]
  },
  {
   "title": "DCP Items Sent/sec by Node",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum without (connection_type, bucket) (rate(kv_dcp_items_sent{cluster_name=~\"$cluster\",bucket=~\"$bucket\",connection_type=~\".+\"}[$__rate_interval]))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "DCP Product Count by Connection Type",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum without (instance, bucket) (kv_dcp_producer_count{cluster_name=~\"$cluster\",bucket=~\"$bucket\",connection_type=~\".+\"})",
     "legendFormat": "{{connection_type}}"
    }
   ]
  },
  {
   "title": "DCP Producer Count by Bucket",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum without (instance, connection_type) (kv_dcp_producer_count{cluster_name=~\"$cluster\",bucket=~\"$bucket\",connection_type=~\".+\"})",
     "legendFormat": "{{bucket}}"
    }
   ]
  },
  {
   "title": "DCP Producer Count by Bucket",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum without (bucket, connection_type) (kv_dcp_producer_count{cluster_name=~\"$cluster\",bucket=~\"$bucket\",connection_type=~\".+\"})",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "DCP Total Data Size by Connection Type",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum without (instance, bucket) (irate(kv_dcp_total_data_size_bytes{cluster_name=~\"$cluster\",bucket=~\"$bucket\",connection_type=~\".+\"}[$__rate_interval]))",
     "legendFormat": "{{connection_type}}"
    }
   ]
  },
  {
   "title": "DCP Total Data Size by Bucket",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum without (instance, connection_type) (irate(kv_dcp_total_data_size_bytes{cluster_name=~\"$cluster\",bucket=~\"$bucket\",connection_type=~\".+\"}[$__rate_interval]))",
     "legendFormat": "{{bucket}}"
    }
   ]
  },
  {
   "title": "DCP Total Data Size by Node",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum without (bucket, connection_type) (irate(kv_dcp_total_data_size_bytes{cluster_name=~\"$cluster\",bucket=~\"$bucket\",connection_type=~\".+\"}[$__rate_interval]))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "DCP Total Data Size (Uncompressed) by Connection Type",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum without (instance, bucket) (irate(kv_dcp_total_uncompressed_data_size_bytes{cluster_name=~\"$cluster\",bucket=~\"$bucket\",connection_type=~\".+\"}[$__rate_interval]))",
     "legendFormat": "{{connection_type}}"
    }
   ]
  },
  {
   "title": "DCP Total Data Size (Uncompressed) by Bucket",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum without (instance, connection_type) (irate(kv_dcp_total_uncompressed_data_size_bytes{cluster_name=~\"$cluster\",bucket=~\"$bucket\",connection_type=~\".+\"}[$__rate_interval]))",
     "legendFormat": "{{bucket}}"
    }
   ]
  },
  {
   "title": "DCP Total Data Size (Uncompressed) by Node",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum without (bucket, connection_type) (irate(kv_dcp_total_uncompressed_data_size_bytes{cluster_name=~\"$cluster\",bucket=~\"$bucket\",connection_type=~\".+\"}[$__rate_interval]))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Performance ($opcode)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 43 },
   "repeat": "opcode",
   "collapsed": true,
   "panels": [
    {
     "title": "$opcode/sec Heatmap",
     "type": "heatmap",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 2 },
     "targets": [
      {
       "expr": "sum by(le) (rate(kv_cmd_duration_seconds_bucket{cluster_name=~\"$cluster\",bucket=~\"$bucket\",instance=~\"$node\",opcode=~\"$opcode\"}[$__rate_interval]))",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "$opcode in Range - Heatmap",
     "type": "heatmap",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 2 },
     "targets": [
      {
       "expr": "sum by(le) (increase(kv_cmd_duration_seconds_bucket{cluster_name=~\"$cluster\",bucket=~\"$bucket\",instance=~\"$node\",opcode=~\"$opcode\"}[$__range]))",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "$opcode All-time Heatmap",
     "type": "heatmap",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 2 },
     "targets": [
      {
       "expr": "sum by(le) (kv_cmd_duration_seconds_bucket{cluster_name=~\"$cluster\",bucket=~\"$bucket\",instance=~\"$node\",opcode=~\"$opcode\"})",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "$opcode/sec - Percentiles",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.5, sum by (le) (rate(kv_cmd_duration_seconds_bucket{cluster_name=~\"$cluster\",bucket=~\"$bucket\",opcode=~\"$opcode\",instance=~\"$node\"}[$__rate_interval])))",
       "legendFormat": "50th Percentile"
      },
      {
       "expr": "histogram_quantile(0.9, sum by (le) (rate(kv_cmd_duration_seconds_bucket{cluster_name=~\"$cluster\",bucket=~\"$bucket\",opcode=~\"$opcode\",instance=~\"$node\"}[$__rate_interval])))",
       "legendFormat": "90th Percentile"
      },
      {
       "expr": "histogram_quantile(0.95, sum by (le) (rate(kv_cmd_duration_seconds_bucket{cluster_name=~\"$cluster\",bucket=~\"$bucket\",opcode=~\"$opcode\",instance=~\"$node\"}[$__rate_interval])))",
       "legendFormat": "95th Percentile"
      },
      {
       "expr": "histogram_quantile(0.99, sum by (le) (rate(kv_cmd_duration_seconds_bucket{cluster_name=~\"$cluster\",bucket=~\"$bucket\",opcode=~\"$opcode\",instance=~\"$node\"}[$__rate_interval])))",
       "legendFormat": "99th Percentile"
      },
      {
       "expr": "histogram_quantile(0.999, sum by (le) (rate(kv_cmd_duration_seconds_bucket{cluster_name=~\"$cluster\",bucket=~\"$bucket\",opcode=~\"$opcode\",instance=~\"$node\"}[$__rate_interval])))",
       "legendFormat": "99.9th Percentile"
      }
     ]
    },
    {
     "title": "$opcode in Range - Percentiles",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.5, sum by (le) (increase(kv_cmd_duration_seconds_bucket{cluster_name=~\"$cluster\",bucket=~\"$bucket\",opcode=~\"$opcode\",instance=~\"$node\"}[$__range])))",
       "legendFormat": "50th Percentile"
      },
      {
       "expr": "histogram_quantile(0.9, sum by (le) (increase(kv_cmd_duration_seconds_bucket{cluster_name=~\"$cluster\",bucket=~\"$bucket\",opcode=~\"$opcode\",instance=~\"$node\"}[$__range])))",
       "legendFormat": "90th Percentile"
      },
      {
       "expr": "histogram_quantile(0.95, sum by (le) (increase(kv_cmd_duration_seconds_bucket{cluster_name=~\"$cluster\",bucket=~\"$bucket\",opcode=~\"$opcode\",instance=~\"$node\"}[$__range])))",
       "legendFormat": "95th Percentile"
      },
      {
       "expr": "histogram_quantile(0.99, sum by (le) (increase(kv_cmd_duration_seconds_bucket{cluster_name=~\"$cluster\",bucket=~\"$bucket\",opcode=~\"$opcode\",instance=~\"$node\"}[$__range])))",
       "legendFormat": "99th Percentile"
      },
      {
       "expr": "histogram_quantile(0.999, sum by (le) (increase(kv_cmd_duration_seconds_bucket{cluster_name=~\"$cluster\",bucket=~\"$bucket\",opcode=~\"$opcode\",instance=~\"$node\"}[$__range])))",
       "legendFormat": "99.9th Percentile"
      }
     ]
    },
    {
     "title": "$opcode All-time - Percentiles",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.5, sum by (le) (kv_cmd_duration_seconds_bucket{cluster_name=~\"$cluster\",bucket=~\"$bucket\",opcode=~\"$opcode\",instance=~\"$node\"}))",
       "legendFormat": "50th Percentile"
      },
      {
       "expr": "histogram_quantile(0.9, sum by (le) (kv_cmd_duration_seconds_bucket{cluster_name=~\"$cluster\",bucket=~\"$bucket\",opcode=~\"$opcode\",instance=~\"$node\"}))",
       "legendFormat": "90th Percentile"
      },
      {
       "expr": "histogram_quantile(0.95, sum by (le) (kv_cmd_duration_seconds_bucket{cluster_name=~\"$cluster\",bucket=~\"$bucket\",opcode=~\"$opcode\",instance=~\"$node\"}))",
       "legendFormat": "95th Percentile"
      },
      {
       "expr": "histogram_quantile(0.99, sum by (le) (kv_cmd_duration_seconds_bucket{cluster_name=~\"$cluster\",bucket=~\"$bucket\",opcode=~\"$opcode\",instance=~\"$node\"}))",
       "legendFormat": "99th Percentile"
      },
      {
       "expr": "histogram_quantile(0.999, sum by (le) (kv_cmd_duration_seconds_bucket{cluster_name=~\"$cluster\",bucket=~\"$bucket\",opcode=~\"$opcode\",instance=~\"$node\"}))",
       "legendFormat": "99.9th Percentile"
      }
     ]
    },
    {
     "title": "Bucket $opcode/sec - 99th Percentile",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum without (instance) (rate(kv_cmd_duration_seconds_bucket{cluster_name=~\"$cluster\",bucket=~\"$bucket\",opcode=~\"$opcode\",instance=~\"$node\"}[$__rate_interval])))",
       "legendFormat": "{{bucket}}"
      }
     ]
    },
    {
     "title": "Bucket $opcode/sec - 99th Percentile",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum without (instance) (rate(kv_cmd_duration_seconds_bucket{cluster_name=~\"$cluster\",bucket=~\"$bucket\",opcode=~\"$opcode\",instance=~\"$node\"}[$__rate_interval])))",
       "legendFormat": "{{bucket}}"
      }
     ]
    },
    {
     "title": "Bucket $opcode All-time - 99th Percentile",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum without (instance) (kv_cmd_duration_seconds_bucket{cluster_name=~\"$cluster\",bucket=~\"$bucket\",opcode=~\"$opcode\",instance=~\"$node\"}))",
       "legendFormat": "{{bucket}}"
      }
     ]
    },
    {
     "title": "Node $opcode/sec - 99th Percentile",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 23 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum by (instance, le) (rate(kv_cmd_duration_seconds_bucket{cluster_name=~\"$cluster\",bucket=~\"$bucket\",opcode=~\"$opcode\",instance=~\"$node\"}[$__rate_interval])))",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Node $opcode in Range - 99th Percentile",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 23 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum by (instance, le) (increase(kv_cmd_duration_seconds_bucket{cluster_name=~\"$cluster\",bucket=~\"$bucket\",opcode=~\"$opcode\",instance=~\"$node\"}[$__range])))",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Node $opcode All-time - 99th Percentile",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 23 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum by (instance, le) (kv_cmd_duration_seconds_bucket{cluster_name=~\"$cluster\",bucket=~\"$bucket\",opcode=~\"$opcode\",instance=~\"$node\"}))",
       "legendFormat": "{{bucket}}"
      }
     ]
    }
   ]
  }
 ]
}