{
 "title": "Couchbase KV Command Performance",
 "tags": [
  "couchbase",
  "data",
  "buckets"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "15s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" },
   {
    "name": "cluster",
    "label": "Cluster",
    "query": {
     "query": "label_values(kv_cmd_duration_seconds_bucket, cluster_name)"
    }
   },
   {
    "name": "bucket",
    "label": "Bucket",
    "query": {
     "query": "label_values(kv_cmd_duration_seconds_bucket{cluster_name=~\"$cluster\"}, bucket)"
    }
   },
   {
    "name": "opcode",
    "label": "OP",
    "query": {
     "query": "label_values(kv_cmd_duration_seconds_bucket{cluster_name=~\"$cluster\",bucket=~\"$bucket\"}, opcode)"
    }
   },
   {
    "name": "node",
    "label": "Node",
    "query": {
     "query": "label_values(kv_cmd_duration_seconds_bucket{cluster_name=~\"$cluster\",bucket=~\"$bucket\"}, instance)"
    }
   }
  ]
 },
 "panels": [
  { "title": "KV Command ($opcode)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "opcode" },
  {
   "title": "$opcode/sec Heatmap",
   "type": "heatmap",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "sum by(le) (rate(kv_cmd_duration_seconds_bucket{cluster_name=~\"$cluster\",bucket=~\"$bucket\",instance=~\"$node\",opcode=~\"$opcode\"}[$__rate_interval]))",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "$opcode in Range - Heatmap",
   "type": "heatmap",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 1 },
   "targets": [
    {
     "expr": "sum by(le) (increase(kv_cmd_duration_seconds_bucket{cluster_name=~\"$cluster\",bucket=~\"$bucket\",instance=~\"$node\",opcode=~\"$opcode\"}[$__range]))",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "$opcode All-time Heatmap",
   "type": "heatmap",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 1 },
   "targets": [
    {
     "expr": "sum by(le) (kv_cmd_duration_seconds_bucket{cluster_name=~\"$cluster\",bucket=~\"$bucket\",instance=~\"$node\",opcode=~\"$opcode\"})",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "$opcode/sec - Percentiles",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum by (le) (rate(kv_cmd_duration_seconds_bucket{cluster_name=~\"$cluster\",bucket=~\"$bucket\",opcode=~\"$opcode\",instance=~\"$node\"}[$__rate_interval])))",
     "legendFormat": "50th Percentile"
    },
    {
     "expr": "histogram_quantile(0.9, sum by (le) (rate(kv_cmd_duration_seconds_bucket{cluster_name=~\"$cluster\",bucket=~\"$bucket\",opcode=~\"$opcode\",instance=~\"$node\"}[$__rate_interval])))",
     "legendFormat": "90th Percentile"
    },
    {
     "expr": "histogram_quantile(0.95, sum by (le) (rate(kv_cmd_duration_seconds_bucket{cluster_name=~\"$cluster\",bucket=~\"$bucket\",opcode=~\"$opcode\",instance=~\"$node\"}[$__rate_interval])))",
     "legendFormat": "95th Percentile"
    },
    {
     "expr": "histogram_quantile(0.99, sum by (le) (rate(kv_cmd_duration_seconds_bucket{cluster_name=~\"$cluster\",bucket=~\"$bucket\",opcode=~\"$opcode\",instance=~\"$node\"}[$__rate_interval])))",
     "legendFormat": "99th Percentile"
    },
    {
     "expr": "histogram_quantile(0.999, sum by (le) (rate(kv_cmd_duration_seconds_bucket{cluster_name=~\"$cluster\",bucket=~\"$bucket\",opcode=~\"$opcode\",instance=~\"$node\"}[$__rate_interval])))",
     "legendFormat": "99.9th Percentile"
    }
   ]
  },
  {
   "title": "$opcode in Range - Percentiles",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum by (le) (increase(kv_cmd_duration_seconds_bucket{cluster_name=~\"$cluster\",bucket=~\"$bucket\",opcode=~\"$opcode\",instance=~\"$node\"}[$__range])))",
     "legendFormat": "50th Percentile"
    },
    {
     "expr": "histogram_quantile(0.9, sum by (le) (increase(kv_cmd_duration_seconds_bucket{cluster_name=~\"$cluster\",bucket=~\"$bucket\",opcode=~\"$opcode\",instance=~\"$node\"}[$__range])))",
     "legendFormat": "90th Percentile"
    },
    {
     "expr": "histogram_quantile(0.95, sum by (le) (increase(kv_cmd_duration_seconds_bucket{cluster_name=~\"$cluster\",bucket=~\"$bucket\",opcode=~\"$opcode\",instance=~\"$node\"}[$__range])))",
     "legendFormat": "95th Percentile"
    },
    {
     "expr": "histogram_quantile(0.99, sum by (le) (increase(kv_cmd_duration_seconds_bucket{cluster_name=~\"$cluster\",bucket=~\"$bucket\",opcode=~\"$opcode\",instance=~\"$node\"}[$__range])))",
     "legendFormat": "99th Percentile"
    },
    {
     "expr": "histogram_quantile(0.999, sum by (le) (increase(kv_cmd_duration_seconds_bucket{cluster_name=~\"$cluster\",bucket=~\"$bucket\",opcode=~\"$opcode\",instance=~\"$node\"}[$__range])))",
     "legendFormat": "99.9th Percentile"
    }
   ]
  },
  {
   "title": "$opcode All-time - Percentiles",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum by (le) (kv_cmd_duration_seconds_bucket{cluster_name=~\"$cluster\",bucket=~\"$bucket\",opcode=~\"$opcode\",instance=~\"$node\"}))",
     "legendFormat": "50th Percentile"
    },
    {
     "expr": "histogram_quantile(0.9, sum by (le) (kv_cmd_duration_seconds_bucket{cluster_name=~\"$cluster\",bucket=~\"$bucket\",opcode=~\"$opcode\",instance=~\"$node\"}))",
     "legendFormat": "90th Percentile"
    },
    {
     "expr": "histogram_quantile(0.95, sum by (le) (kv_cmd_duration_seconds_bucket{cluster_name=~\"$cluster\",bucket=~\"$bucket\",opcode=~\"$opcode\",instance=~\"$node\"}))",
     "legendFormat": "95th Percentile"
    },
    {
     "expr": "histogram_quantile(0.99, sum by (le) (kv_cmd_duration_seconds_bucket{cluster_name=~\"$cluster\",bucket=~\"$bucket\",opcode=~\"$opcode\",instance=~\"$node\"}))",
     "legendFormat": "99th Percentile"
    },
    {
     "expr": "histogram_quantile(0.999, sum by (le) (kv_cmd_duration_seconds_bucket{cluster_name=~\"$cluster\",bucket=~\"$bucket\",opcode=~\"$opcode\",instance=~\"$node\"}))",
     "legendFormat": "99.9th Percentile"
    }
   ]
  },
  {
   "title": "Bucket $opcode/sec - 99th Percentile",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum without (instance) (rate(kv_cmd_duration_seconds_bucket{cluster_name=~\"$cluster\",bucket=~\"$bucket\",opcode=~\"$opcode\",instance=~\"$node\"}[$__rate_interval])))",
     "legendFormat": "{{bucket}}"
    }
   ]
  },
  {
   "title": "Bucket $opcode/sec - 99th Percentile",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum without (instance) (rate(kv_cmd_duration_seconds_bucket{cluster_name=~\"$cluster\",bucket=~\"$bucket\",opcode=~\"$opcode\",instance=~\"$node\"}[$__rate_interval])))",
     "legendFormat": "{{bucket}}"
    }
   ]
  },
  {
   "title": "Bucket $opcode All-time - 99th Percentile",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum without (instance) (kv_cmd_duration_seconds_bucket{cluster_name=~\"$cluster\",bucket=~\"$bucket\",opcode=~\"$opcode\",instance=~\"$node\"}))",
     "legendFormat": "{{bucket}}"
    }
   ]
  },
  {
   "title": "Node $opcode/sec - 99th Percentile",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by (instance, le) (rate(kv_cmd_duration_seconds_bucket{cluster_name=~\"$cluster\",bucket=~\"$bucket\",opcode=~\"$opcode\",instance=~\"$node\"}[$__rate_interval])))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Node $opcode in Range - 99th Percentile",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by (instance, le) (increase(kv_cmd_duration_seconds_bucket{cluster_name=~\"$cluster\",bucket=~\"$bucket\",opcode=~\"$opcode\",instance=~\"$node\"}[$__range])))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Node $opcode All-time - 99th Percentile",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by (instance, le) (kv_cmd_duration_seconds_bucket{cluster_name=~\"$cluster\",bucket=~\"$bucket\",opcode=~\"$opcode\",instance=~\"$node\"}))",
     "legendFormat": "{{bucket}}"
    }
   ]
  }
 ]
}