{
 "title": "Magma - Node & Bucket",
 "tags": [
  "Couchbase",
  "buckets",
  "data",
  "magma"
 ],
 "time": { "from": "now-1d", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" },
   {
    "name": "cluster",
    "label": "Cluster",
    "query": {
     "query": "label_values(kv_auth_cmds, cluster_name)"
    }
   },
   {
    "name": "bucket",
    "label": "Bucket",
    "query": {
     "query": "label_values(kv_ep_magma_flushes{cluster_name=~\"$cluster\"}, bucket)"
    }
   },
   {
    "name": "node",
    "label": "Node",
    "query": {
     "query": "label_values(kv_auth_cmds{cluster_name=~\"$cluster\"}, instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "OPS rate",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(kv_ep_magma_gets{cluster_name=~\"$cluster\",bucket=~\"$bucket\",instance=~\"$node\"}[1m])",
     "legendFormat": "gets"
    },
    {
     "expr": "rate(kv_ep_magma_sets{cluster_name=~\"$cluster\",bucket=~\"$bucket\",instance=~\"$node\"}[1m])",
     "legendFormat": "sets"
    },
    {
     "expr": "rate(kv_ep_magma_inserts{cluster_name=~\"$cluster\",bucket=~\"$bucket\",instance=~\"$node\"}[1m])",
     "legendFormat": "inserts"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "kv_ep_magma_write_cache_mem_used_bytes{cluster_name=~\"$cluster\",bucket=~\"$bucket\",instance=~\"$node\"}",
     "legendFormat": "write cache"
    },
    {
     "expr": "kv_ep_magma_bloom_filter_mem_used_bytes{cluster_name=~\"$cluster\",bucket=~\"$bucket\",instance=~\"$node\"}",
     "legendFormat": "filter"
    },
    {
     "expr": "kv_ep_magma_block_cache_mem_used_bytes{cluster_name=~\"$cluster\",bucket=~\"$bucket\",instance=~\"$node\"}",
     "legendFormat": "block cache"
    },
    {
     "expr": "kv_ep_magma_table_meta_mem_used_bytes{cluster_name=~\"$cluster\",bucket=~\"$bucket\",instance=~\"$node\"}",
     "legendFormat": "table meta"
    },
    {
     "expr": "kv_ep_magma_table_object_mem_used_bytes{cluster_name=~\"$cluster\",bucket=~\"$bucket\",instance=~\"$node\"}",
     "legendFormat": "table object"
    },
    {
     "expr": "kv_ep_magma_buffer_mem_used_bytes{cluster_name=~\"$cluster\",bucket=~\"$bucket\",instance=~\"$node\"}",
     "legendFormat": "buffer"
    },
    {
     "expr": "kv_ep_magma_wal_mem_used_bytes{cluster_name=~\"$cluster\",bucket=~\"$bucket\",instance=~\"$node\"}",
     "legendFormat": "wal"
    },
    {
     "expr": "kv_ep_magma_total_mem_used_bytes{cluster_name=~\"$cluster\",bucket=~\"$bucket\",instance=~\"$node\"}",
     "legendFormat": "total"
    },
    {
     "expr": "kv_ep_magma_histogram_mem_used_bytes{cluster_name=~\"$cluster\",bucket=~\"$bucket\",instance=~\"$node\"}",
     "legendFormat": "histogram"
    },
    {
     "expr": "kv_ep_magma_lsmtree_object_mem_used_bytes{cluster_name=~\"$cluster\",bucket=~\"$bucket\",instance=~\"$node\"}",
     "legendFormat": "lsmtree object"
    },
    {
     "expr": "kv_ep_magma_tree_snapshot_mem_used_bytes{cluster_name=~\"$cluster\",bucket=~\"$bucket\",instance=~\"$node\"}",
     "legendFormat": "tree snapshot"
    },
    {
     "expr": "kv_domain_memory_used_bytes{bucket=\"$bucket\",cluster_name=~\"$cluster\",domain=\"secondary\",instance=~\"$node\"}",
     "legendFormat": "secondary domain"
    },
    {
     "expr": "kv_domain_memory_used_bytes{bucket=\"$bucket\",cluster_name=~\"$cluster\",domain=\"primary\",instance=~\"$node\"}",
     "legendFormat": "primary domain"
    }
   ]
  },
  {
   "title": "Thread pool CPU",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (thread_pool, instance) (rate(kv_thread_cpu_usage_seconds{cluster_name=~\"$cluster\",instance=~\"$node\"}[6m]))",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "Compaction rate",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(kv_ep_magma_compactions{cluster_name=~\"$cluster\",bucket=~\"$bucket\",instance=~\"$node\"}[1m])",
     "legendFormat": "compactions"
    },
    {
     "expr": "rate(kv_magma_compactions{bucket=\"$bucket\",cluster_name=~\"$cluster\",for=\"keyindex\",instance=~\"$node\"}[1m])",
     "legendFormat": "key"
    },
    {
     "expr": "rate(kv_magma_compactions{bucket=\"$bucket\",cluster_name=~\"$cluster\",for=\"seqindex\",instance=~\"$node\"}[1m])",
     "legendFormat": "seq"
    },
    {
     "expr": "rate(kv_ep_magma_ttl_compactions{cluster_name=~\"$cluster\",bucket=~\"$bucket\",instance=~\"$node\"}[1m])",
     "legendFormat": "ttl"
    },
    {
     "expr": "rate(kv_ep_magma_filecount_compactions{cluster_name=~\"$cluster\",bucket=~\"$bucket\",instance=~\"$node\"}[1m])",
     "legendFormat": "filecount"
    },
    {
     "expr": "rate(kv_ep_magma_keyindex_filecount_compactions{cluster_name=~\"$cluster\",bucket=~\"$bucket\",instance=~\"$node\"}[1m])",
     "legendFormat": "key filecount"
    },
    {
     "expr": "rate(kv_ep_magma_seqindex_filecount_compactions{cluster_name=~\"$cluster\",bucket=~\"$bucket\",instance=~\"$node\"}[1m])",
     "legendFormat": "seq filecount"
    },
    {
     "expr": "rate(kv_ep_magma_writer_compactions{cluster_name=~\"$cluster\",bucket=~\"$bucket\",instance=~\"$node\"}[1m])",
     "legendFormat": "writer"
    },
    {
     "expr": "rate(kv_ep_magma_keyindex_writer_compactions{cluster_name=~\"$cluster\",bucket=~\"$bucket\",instance=~\"$node\"}[1m])",
     "legendFormat": "key writer"
    },
    {
     "expr": "rate(kv_ep_magma_seqindex_writer_compactions{cluster_name=~\"$cluster\",bucket=~\"$bucket\",instance=~\"$node\"}[1m])",
     "legendFormat": "seq writer"
    },
    {
     "expr": "rate(kv_ep_magma_seqindex_data_compactions{cluster_name=~\"$cluster\",bucket=~\"$bucket\",instance=~\"$node\"}[1m])",
     "legendFormat": "seq data level"
    }
   ]
  },
  {
   "title": "Flush rate",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(kv_ep_magma_flushes{cluster_name=~\"$cluster\",bucket=~\"$bucket\",instance=~\"$node\"}[1m])",
     "legendFormat": "flushes"
    }
   ]
  },
  {
   "title": "Tables",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "kv_ep_magma_tables{cluster_name=~\"$cluster\",bucket=~\"$bucket\",instance=~\"$node\"}",
     "legendFormat": "tables"
    },
    {
     "expr": "rate(kv_ep_magma_tables_created{cluster_name=~\"$cluster\",bucket=~\"$bucket\",instance=~\"$node\"}[1m])",
     "legendFormat": "creation rate"
    },
    {
     "expr": "rate(kv_ep_magma_tables_deleted{cluster_name=~\"$cluster\",bucket=~\"$bucket\",instance=~\"$node\"}[1m])",
     "legendFormat": "deletion rate"
    }
   ]
  },
  {
   "title": "Block cache",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(kv_ep_magma_block_cache_hits{cluster_name=~\"$cluster\",bucket=~\"$bucket\",instance=~\"$node\"}[1m])",
     "legendFormat": "hit rate"
    },
    {
     "expr": "rate(kv_ep_magma_block_cache_misses{cluster_name=~\"$cluster\",bucket=~\"$bucket\",instance=~\"$node\"}[1m])",
     "legendFormat": "miss rate"
    },
    {
     "expr": "kv_ep_magma_index_resident_ratio_ratio{cluster_name=~\"$cluster\",bucket=~\"$bucket\",instance=~\"$node\"} * 100",
     "legendFormat": "index resident %"
    }
   ]
  },
  { "title": "Disk IO", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 36 } },
  {
   "title": "Write bytes rate",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(kv_ep_magma_write_bytes_bytes{cluster_name=~\"$cluster\",bucket=~\"$bucket\",instance=~\"$node\"}[1m])",
     "legendFormat": "total"
    },
    {
     "expr": "rate(kv_ep_magma_write_bytes_compact_bytes{cluster_name=~\"$cluster\",bucket=~\"$bucket\",instance=~\"$node\"}[1m])",
     "legendFormat": "compactions"
    },
    {
     "expr": "rate(kv_magma_write_bytes_{bucket=\"$bucket\",cluster_name=~\"$cluster\",for=\"keyindex\",instance=~\"$node\"}[1m])",
     "legendFormat": "keyindex"
    },
    {
     "expr": "rate(kv_magma_write_bytes_bytes{bucket=\"$bucket\",cluster_name=~\"$cluster\",for=\"seqindex\",instance=~\"$node\"}[1m])",
     "legendFormat": "seqindex"
    },
    {
     "expr": "rate(kv_ep_magma_seqindex_delta_write_bytes_bytes{cluster_name=~\"$cluster\",bucket=~\"$bucket\",instance=~\"$node\"}[1m])",
     "legendFormat": "seqindex delta levels"
    },
    {
     "expr": "rate(kv_magma_write_bytes_filecount_compact_bytes{bucket=\"$bucket\",cluster_name=~\"$cluster\",for=\"keyindex\",instance=~\"$node\"}[1m])",
     "legendFormat": "keyindex filecount"
    },
    {
     "expr": "rate(kv_magma_write_bytes_filecount_compact_bytes{bucket=\"$bucket\",cluster_name=~\"$cluster\",for=\"seqindex\",instance=~\"$node\"}[1m])",
     "legendFormat": "seqindex filecount"
    }
   ]
  },
  {
   "title": "Write bytes",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "kv_ep_magma_write_bytes_bytes{cluster_name=~\"$cluster\",bucket=~\"$bucket\",instance=~\"$node\"}",
     "legendFormat": "total"
    },
    {
     "expr": "kv_ep_magma_write_bytes_compact_bytes{cluster_name=~\"$cluster\",bucket=~\"$bucket\",instance=~\"$node\"}",
     "legendFormat": "compactions"
    },
    {
     "expr": "kv_magma_write_bytes_{bucket=\"$bucket\",cluster_name=~\"$cluster\",for=\"keyindex\",instance=~\"$node\"}",
     "legendFormat": "keyindex"
    },
    {
     "expr": "kv_magma_write_bytes_bytes{bucket=\"$bucket\",cluster_name=~\"$cluster\",for=\"seqindex\",instance=~\"$node\"}",
     "legendFormat": "seqindex"
    },
    {
     "expr": "kv_ep_magma_seqindex_delta_write_bytes_bytes{cluster_name=~\"$cluster\",bucket=~\"$bucket\",instance=~\"$node\"}",
     "legendFormat": "seqindex delta levels"
    },
    {
     "expr": "kv_magma_write_bytes_filecount_compact_bytes{bucket=\"$bucket\",cluster_name=~\"$cluster\",for=\"keyindex\",instance=~\"$node\"}",
     "legendFormat": "keyindex filecount"
    },
    {
     "expr": "kv_magma_write_bytes_filecount_compact_bytes{bucket=\"$bucket\",cluster_name=~\"$cluster\",for=\"seqindex\",instance=~\"$node\"}",
     "legendFormat": "seqindex filecount"
    }
   ]
  },
  {
   "title": "Bytes incoming rate",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "rate(kv_ep_magma_bytes_incoming_bytes{cluster_name=~\"$cluster\",bucket=~\"$bucket\",instance=~\"$node\"}[1m])",
     "legendFormat": "total"
    },
    {
     "expr": "rate(kv_magma_bytes_incoming_bytes{bucket=\"$bucket\",cluster_name=~\"$cluster\",for=\"keyindex\",instance=~\"$node\"}[1m])",
     "legendFormat": "keyindex"
    },
    {
     "expr": "rate(kv_magma_bytes_incoming_bytes{bucket=\"$bucket\",cluster_name=~\"$cluster\",for=\"seqindex\",instance=~\"$node\"}[1m])",
     "legendFormat": "seqindex"
    },
    {
     "expr": "rate(kv_ep_magma_seqindex_delta_bytes_incoming_bytes{cluster_name=~\"$cluster\",bucket=~\"$bucket\",instance=~\"$node\"}[1m])",
     "legendFormat": "seqindex delta levels"
    }
   ]
  },
  {
   "title": "Bytes incoming",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "kv_ep_magma_bytes_incoming_bytes{cluster_name=~\"$cluster\",bucket=~\"$bucket\",instance=~\"$node\"}",
     "legendFormat": "total"
    },
    {
     "expr": "kv_magma_bytes_incoming_bytes{bucket=\"$bucket\",cluster_name=~\"$cluster\",for=\"keyindex\",instance=~\"$node\"}",
     "legendFormat": "keyindex"
    },
    {
     "expr": "kv_magma_bytes_incoming_bytes{bucket=\"$bucket\",cluster_name=~\"$cluster\",for=\"seqindex\",instance=~\"$node\"}",
     "legendFormat": "seqindex"
    },
    {
     "expr": "kv_ep_magma_seqindex_delta_bytes_incoming_bytes{cluster_name=~\"$cluster\",bucket=~\"$bucket\",instance=~\"$node\"}",
     "legendFormat": "seqindex delta levels"
    }
   ]
  },
  {
   "title": "Read bytes rate",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 55 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "rate(kv_ep_magma_read_bytes_bytes{cluster_name=~\"$cluster\",bucket=~\"$bucket\",instance=~\"$node\"}[1m])",
     "legendFormat": "total"
    },
    {
     "expr": "rate(kv_ep_magma_read_bytes_compact_bytes{cluster_name=~\"$cluster\",bucket=~\"$bucket\",instance=~\"$node\"}[1m])",
     "legendFormat": "compactions"
    },
    {
     "expr": "rate(kv_ep_magma_read_bytes_get_bytes{cluster_name=~\"$cluster\",bucket=~\"$bucket\",instance=~\"$node\"}[1m])",
     "legendFormat": "gets"
    }
   ]
  },
  {
   "title": "Read bytes",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 55 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "kv_ep_magma_read_bytes_bytes{cluster_name=~\"$cluster\",bucket=~\"$bucket\",instance=~\"$node\"}",
     "legendFormat": "total"
    },
    {
     "expr": "kv_ep_magma_read_bytes_compact_bytes{cluster_name=~\"$cluster\",bucket=~\"$bucket\",instance=~\"$node\"}",
     "legendFormat": "compactions"
    },
    {
     "expr": "kv_ep_magma_read_bytes_get_bytes{cluster_name=~\"$cluster\",bucket=~\"$bucket\",instance=~\"$node\"}",
     "legendFormat": "gets"
    }
   ]
  },
  {
   "title": "Bytes outgoing rate",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 64 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "rate(kv_ep_magma_bytes_outgoing_bytes{cluster_name=~\"$cluster\",bucket=~\"$bucket\",instance=~\"$node\"}[2m])",
     "legendFormat": "outgoing"
    }
   ]
  },
  {
   "title": "Bytes outgoing",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 64 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "kv_ep_magma_bytes_outgoing_bytes{cluster_name=~\"$cluster\",bucket=~\"$bucket\",instance=~\"$node\"}",
     "legendFormat": "outgoing"
    }
   ]
  },
  {
   "title": "Read IO rate",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 73 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(kv_ep_magma_readio{cluster_name=~\"$cluster\",bucket=~\"$bucket\",instance=~\"$node\"}[20s])",
     "legendFormat": "readio"
    }
   ]
  },
  { "title": "Size", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 82 } },
  {
   "title": "Disk usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 83 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "kv_ep_magma_total_disk_usage_bytes{cluster_name=~\"$cluster\",bucket=~\"$bucket\",instance=~\"$node\"}",
     "legendFormat": "total"
    },
    {
     "expr": "kv_ep_magma_wal_disk_usage_bytes{cluster_name=~\"$cluster\",bucket=~\"$bucket\",instance=~\"$node\"}",
     "legendFormat": "wal"
    },
    {
     "expr": "kv_ep_magma_checkpoint_disk_usage_bytes{cluster_name=~\"$cluster\",bucket=~\"$bucket\",instance=~\"$node\"}",
     "legendFormat": "checkpoint"
    },
    {
     "expr": "kv_ep_magma_active_disk_usage_bytes{cluster_name=~\"$cluster\",bucket=~\"$bucket\",instance=~\"$node\"}",
     "legendFormat": "active"
    },
    {
     "expr": "couch_docs_actual_disk_size{cluster_name=~\"$cluster\",bucket=~\"$bucket\",instance=~\"$node\"}",
     "legendFormat": "couch_docs_actual"
    }
   ]
  },
  {
   "title": "Logical size",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 83 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "kv_ep_magma_logical_data_size_bytes{cluster_name=~\"$cluster\",bucket=~\"$bucket\",instance=~\"$node\"}",
     "legendFormat": "data"
    },
    {
     "expr": "kv_ep_magma_logical_disk_size_bytes{cluster_name=~\"$cluster\",bucket=~\"$bucket\",instance=~\"$node\"}",
     "legendFormat": "disk"
    },
    {
     "expr": "kv_ep_magma_history_logical_data_size_bytes{cluster_name=~\"$cluster\",bucket=~\"$bucket\",instance=~\"$node\"}",
     "legendFormat": "history data"
    },
    {
     "expr": "kv_ep_magma_history_logical_disk_size_bytes{cluster_name=~\"$cluster\",bucket=~\"$bucket\",instance=~\"$node\"}",
     "legendFormat": "history disk"
    }
   ]
  },
  {
   "title": "Data block compression",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 92 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "kv_ep_magma_data_blocks_uncompressed_size{cluster_name=~\"$cluster\",bucket=~\"$bucket\",instance=~\"$node\"}",
     "legendFormat": "uncompressed"
    },
    {
     "expr": "kv_ep_magma_data_blocks_compressed_size{cluster_name=~\"$cluster\",bucket=~\"$bucket\",instance=~\"$node\"}",
     "legendFormat": "compressed"
    },
    {
     "expr": "kv_ep_magma_data_blocks_space_reduction_estimate_pct_ratio{cluster_name=~\"$cluster\",bucket=~\"$bucket\",instance=~\"$node\"} * 100",
     "legendFormat": "space reduction %"
    }
   ]
  },
  {
   "title": "Fragmentation %",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 92 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "kv_ep_magma_fragmentation_ratio{cluster_name=~\"$cluster\",bucket=~\"$bucket\",instance=~\"$node\"} * 100",
     "legendFormat": "fragmentation%"
    }
   ]
  },
  { "title": "History", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 101 } },
  {
   "title": "History start timestamp",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 102 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "kv_ep_db_history_start_timestamp_seconds{cluster_name=~\"$cluster\",bucket=~\"$bucket\",instance=~\"$node\"}",
     "legendFormat": "timestamp"
    }
   ]
  },
  {
   "title": "History eviction bytes rate",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 102 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "rate(kv_ep_magma_history_size_evicted_bytes{cluster_name=~\"$cluster\",bucket=~\"$bucket\",instance=~\"$node\"}[20s])",
     "legendFormat": "size"
    },
    {
     "expr": "rate(kv_ep_magma_history_time_evicted_bytes{cluster_name=~\"$cluster\",bucket=~\"$bucket\",instance=~\"$node\"}[20s])",
     "legendFormat": "time"
    }
   ]
  },
  { "title": "WriteAmp", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 111 } },
  {
   "title": "Overall write amp breakdown",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 112 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "avg by (job, instance) (rate(kv_ep_magma_write_bytes_bytes{cluster_name=~\"$cluster\",bucket=~\"$bucket\",instance=~\"$node\"}[15m])) / avg by (job, instance) (rate(kv_ep_magma_bytes_incoming_bytes{cluster_name=~\"$cluster\",bucket=~\"$bucket\",instance=~\"$node\"}[15m]))",
     "legendFormat": "overall"
    },
    {
     "expr": "avg by (job, instance) (rate(kv_magma_write_bytes_bytes{bucket=\"$bucket\",cluster_name=~\"$cluster\",for=\"keyindex\",instance=~\"$node\"}[15m])) / avg by (job, instance) (rate(kv_ep_magma_bytes_incoming_bytes{cluster_name=~\"$cluster\",bucket=~\"$bucket\",instance=~\"$node\"}[15m]))",
     "legendFormat": "keyindex"
    },
    {
     "expr": "avg by (job, instance) (rate(kv_magma_write_bytes_bytes{bucket=\"$bucket\",cluster_name=~\"$cluster\",for=\"seqindex\",instance=~\"$node\"}[15m])) / avg by (job, instance) (rate(kv_ep_magma_bytes_incoming_bytes{cluster_name=~\"$cluster\",bucket=~\"$bucket\",instance=~\"$node\"}[15m]))",
     "legendFormat": "seqindex"
    },
    {
     "expr": "avg by (job, instance) (rate(kv_ep_magma_seqindex_delta_write_bytes_bytes{cluster_name=~\"$cluster\",bucket=~\"$bucket\",instance=~\"$node\"}[15m])) / avg by (job, instance) (rate(kv_ep_magma_bytes_incoming_bytes{cluster_name=~\"$cluster\",bucket=~\"$bucket\",instance=~\"$node\"}[15m]))",
     "legendFormat": "seqindex delta"
    },
    {
     "expr": "(avg by (job, instance) (rate(kv_magma_write_bytes_bytes{bucket=\"$bucket\",cluster_name=~\"$cluster\",for=\"seqindex\",instance=~\"$node\"}[15m])) - avg by (job, instance) (rate(kv_ep_magma_seqindex_delta_write_bytes_bytes{cluster_name=~\"$cluster\",bucket=~\"$bucket\",instance=~\"$node\"}[15m]))) / avg by (job, instance) (rate(kv_ep_magma_bytes_incoming_bytes{cluster_name=~\"$cluster\",bucket=~\"$bucket\",instance=~\"$node\"}[15m]))",
     "legendFormat": "seqindex data"
    }
   ]
  },
  {
   "title": "Key index write amp",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 112 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "rate(kv_magma_write_bytes_bytes{bucket=\"$bucket\",cluster_name=~\"$cluster\",for=\"keyindex\",instance=~\"$node\"}[15m])",
     "legendFormat": "write bytes"
    },
    {
     "expr": "rate(kv_magma_bytes_incoming_bytes{bucket=\"$bucket\",cluster_name=~\"$cluster\",for=\"keyindex\",instance=~\"$node\"}[15m])",
     "legendFormat": "bytes incoming"
    }
   ]
  },
  {
   "title": "Seq index write amp",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 121 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "rate(kv_magma_write_bytes_bytes{bucket=\"$bucket\",cluster_name=~\"$cluster\",for=\"seqindex\",instance=~\"$node\"}[15m])",
     "legendFormat": "write bytes"
    },
    {
     "expr": "rate(kv_magma_bytes_incoming_bytes{bucket=\"$bucket\",cluster_name=~\"$cluster\",for=\"seqindex\",instance=~\"$node\"}[15m])",
     "legendFormat": "bytes incoming"
    }
   ]
  },
  {
   "title": "Seq index data level write amp",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 121 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "rate(kv_ep_magma_seqindex_delta_write_bytes_bytes{cluster_name=~\"$cluster\",bucket=~\"$bucket\",instance=~\"$node\"}[15m])",
     "legendFormat": "delta write bytes"
    },
    {
     "expr": "rate(kv_ep_magma_seqindex_delta_bytes_incoming_bytes{cluster_name=~\"$cluster\",bucket=~\"$bucket\",instance=~\"$node\"}[15m])",
     "legendFormat": "delta bytes incoming"
    },
    {
     "expr": "rate(kv_magma_write_bytes_bytes{bucket=\"$bucket\",cluster_name=~\"$cluster\",for=\"seqindex\",instance=~\"$node\"}[15m])",
     "legendFormat": "write bytes"
    },
    {
     "expr": "rate(kv_magma_bytes_incoming_bytes{bucket=\"$bucket\",cluster_name=~\"$cluster\",for=\"seqindex\",instance=~\"$node\"}[15m])",
     "legendFormat": "bytes incoming"
    }
   ]
  },
  {
   "title": "Seq index delta levels write amp",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 130 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "rate(kv_ep_magma_seqindex_delta_write_bytes_bytes{cluster_name=~\"$cluster\",bucket=~\"$bucket\",instance=~\"$node\"}[15m])",
     "legendFormat": "write bytes"
    },
    {
     "expr": "rate(kv_ep_magma_seqindex_delta_bytes_incoming_bytes{cluster_name=~\"$cluster\",bucket=~\"$bucket\",instance=~\"$node\"}[15m])",
     "legendFormat": "bytes incoming"
    }
   ]
  }
 ]
}