{
 "title": "Couchbase Magma & Change History Dashboard",
 "tags": [
  "Couchbase",
  "buckets",
  "data",
  "magma"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" },
   {
    "name": "cluster",
    "label": "Cluster",
    "query": {
     "query": "label_values(kv_auth_cmds, cluster_name)"
    }
   },
   {
    "name": "bucket",
    "label": "Bucket",
    "query": {
     "query": "label_values(kv_ep_magma_flushes{cluster_name=~\"$cluster\"}, bucket)"
    }
   },
   {
    "name": "node",
    "label": "Node",
    "query": {
     "query": "label_values(kv_auth_cmds{cluster_name=~\"$cluster\"}, instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Disk Usage & Storage Efficiency",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }
  },
  {
   "title": "Total Disk Usage (Bytes)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 7, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(kv_ep_magma_total_disk_usage_bytes{cluster_name=~\"$cluster\",bucket=~\"$bucket\",instance=~\"$node\"})  by (bucket)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Active Disk Usage (Bytes)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 7, "x": 7, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(kv_ep_magma_active_disk_usage_bytes{cluster_name=~\"$cluster\",bucket=~\"$bucket\",instance=~\"$node\"})  by (bucket)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Logical Data Size (Bytes)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 7, "x": 14, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(kv_ep_magma_logical_data_size_bytes{cluster_name=~\"$cluster\",bucket=~\"$bucket\",instance=~\"$node\"})  by (bucket)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Compressed Data Blocks Size (Bytes)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 7, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(kv_ep_magma_data_blocks_compressed_size{cluster_name=~\"$cluster\",bucket=~\"$bucket\",instance=~\"$node\"})  by (bucket)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Data Compression Ratio",
   "type": "stat",
   "gridPos": { "h": 9, "w": 7, "x": 7, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kv_ep_magma_data_blocks_compression_ratio_ratio{cluster_name=~\"$cluster\",bucket=~\"$bucket\",instance=~\"$node\"})  by (bucket)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Memory Usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 } },
  {
   "title": "Total Memory Usage (Bytes)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 7, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(kv_ep_magma_total_mem_used_bytes{cluster_name=~\"$cluster\",bucket=~\"$bucket\",instance=~\"$node\"})  by (bucket)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Block Cache Memory Usage (Bytes)",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 7, "x": 7, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kv_ep_magma_block_cache_mem_used_bytes{cluster_name=~\"$cluster\",bucket=~\"$bucket\",instance=~\"$node\"})  by (bucket)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Histogram Memory Usage (Bytes)",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 7, "x": 14, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kv_ep_magma_histogram_mem_used_bytes{cluster_name=~\"$cluster\",bucket=~\"$bucket\",instance=~\"$node\"})  by (bucket)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "I/O Performance", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 } },
  {
   "title": "Total Read Bytes",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 7, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(kv_ep_magma_read_bytes_bytes{cluster_name=~\"$cluster\",bucket=~\"$bucket\",instance=~\"$node\"})  by (bucket)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Write Bytes",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 7, "x": 7, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(kv_ep_magma_write_bytes_bytes{cluster_name=~\"$cluster\",bucket=~\"$bucket\",instance=~\"$node\"})  by (bucket)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Write Cache Memory Usage (Bytes)",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 7, "x": 14, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kv_ep_magma_write_cache_mem_used_bytes{cluster_name=~\"$cluster\",bucket=~\"$bucket\",instance=~\"$node\"})  by (bucket)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Write Cache Efficiency Ratio",
   "type": "stat",
   "gridPos": { "h": 9, "w": 7, "x": 0, "y": 39 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kv_ep_magma_write_cache_ratio{cluster_name=~\"$cluster\",bucket=~\"$bucket\",instance=~\"$node\"})  by (bucket)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Cache Performance", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 48 } },
  {
   "title": "Block Cache Hits",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 7, "x": 0, "y": 49 },
   "targets": [
    {
     "expr": "sum(kv_ep_magma_block_cache_hits{cluster_name=~\"$cluster\",bucket=~\"$bucket\",instance=~\"$node\"})  by (bucket)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Block Cache Misses",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 7, "x": 7, "y": 49 },
   "targets": [
    {
     "expr": "sum(kv_ep_magma_block_cache_misses{cluster_name=~\"$cluster\",bucket=~\"$bucket\",instance=~\"$node\"})  by (bucket)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Read Amplification Ratio",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 7, "x": 14, "y": 49 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kv_ep_magma_readamp_ratio{cluster_name=~\"$cluster\",bucket=~\"$bucket\",instance=~\"$node\"})  by (bucket)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Compactions", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 58 } },
  {
   "title": "Total Compactions",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 7, "x": 0, "y": 59 },
   "targets": [
    {
     "expr": "sum(kv_ep_magma_compactions{cluster_name=~\"$cluster\",bucket=~\"$bucket\",instance=~\"$node\"})  by (bucket)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "TTL-Based Compactions",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 7, "x": 7, "y": 59 },
   "targets": [
    {
     "expr": "sum(kv_ep_magma_ttl_compactions{cluster_name=~\"$cluster\",bucket=~\"$bucket\",instance=~\"$node\"})  by (bucket)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Writer Compactions",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 7, "x": 14, "y": 59 },
   "targets": [
    {
     "expr": "sum(kv_ep_magma_writer_compactions{cluster_name=~\"$cluster\",bucket=~\"$bucket\",instance=~\"$node\"})  by (bucket)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Fragmentation", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 68 } },
  {
   "title": "Fragmentation Percentage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 7, "x": 0, "y": 69 },
   "targets": [
    {
     "expr": "sum(kv_ep_magma_fragmentation_percentage{cluster_name=~\"$cluster\",bucket=~\"$bucket\",instance=~\"$node\"})  by (bucket)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Bloom Filter Efficiency", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 78 } },
  {
   "title": "Bloom Filter Accuracy",
   "type": "stat",
   "gridPos": { "h": 9, "w": 7, "x": 0, "y": 79 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kv_ep_magma_bloom_filter_accuracy{cluster_name=~\"$cluster\",bucket=~\"$bucket\",instance=~\"$node\"})  by (bucket)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Bloom Filter Memory Usage (Bytes)",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 7, "x": 7, "y": 79 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kv_ep_magma_bloom_filter_mem_used_bytes{cluster_name=~\"$cluster\",bucket=~\"$bucket\",instance=~\"$node\"})  by (bucket)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Checkpointing", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 88 } },
  {
   "title": "Maximum Checkpoints Allowed",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 7, "x": 0, "y": 89 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kv_ep_magma_max_checkpoints{cluster_name=~\"$cluster\",bucket=~\"$bucket\",instance=~\"$node\"})  by (bucket)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Checkpoint Disk Usage (Bytes)",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 7, "x": 7, "y": 89 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kv_ep_magma_checkpoint_disk_usage_bytes{cluster_name=~\"$cluster\",bucket=~\"$bucket\",instance=~\"$node\"})  by (bucket)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Throughput & Efficiency", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 98 } },
  {
   "title": "Incoming Data Bytes",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 7, "x": 0, "y": 99 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kv_ep_magma_bytes_incoming_bytes{cluster_name=~\"$cluster\",bucket=~\"$bucket\",instance=~\"$node\"})  by (bucket)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Outgoing Data Bytes",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 7, "x": 7, "y": 99 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kv_ep_magma_bytes_outgoing_bytes{cluster_name=~\"$cluster\",bucket=~\"$bucket\",instance=~\"$node\"})  by (bucket)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Read Amplification (Get Operations)",
   "type": "stat",
   "gridPos": { "h": 9, "w": 7, "x": 14, "y": 99 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kv_ep_magma_readamp_get_ratio{cluster_name=~\"$cluster\",bucket=~\"$bucket\",instance=~\"$node\"})  by (bucket)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Change History", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 108 } },
  {
   "title": "Total Enqueued Items (Both Magma and Couchstore))",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 7, "x": 0, "y": 109 },
   "targets": [
    {
     "expr": "sum(kv_ep_total_enqueued{cluster_name=~\"$cluster\",bucket=~\"$bucket\",instance=~\"$node\"})  by (bucket)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Evicted History by Time (Bytes)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 7, "x": 7, "y": 109 },
   "targets": [
    {
     "expr": "sum(kv_ep_magma_history_time_evicted_bytes{cluster_name=~\"$cluster\",bucket=~\"$bucket\",instance=~\"$node\"})  by (bucket)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Evicted History by Size (Bytes)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 7, "x": 14, "y": 109 },
   "targets": [
    {
     "expr": "sum(kv_ep_magma_history_size_evicted_bytes{cluster_name=~\"$cluster\",bucket=~\"$bucket\",instance=~\"$node\"})  by (bucket)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Database History File Size (Bytes) (Both Magma and Couchstore)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 7, "x": 0, "y": 119 },
   "targets": [
    {
     "expr": "sum(kv_ep_db_history_file_size_bytes{cluster_name=~\"$cluster\",bucket=~\"$bucket\",instance=~\"$node\"})  by (bucket)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Max History Disk Size per VBucket (Bytes) (Both Magma and Couchstore)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 7, "x": 7, "y": 119 },
   "targets": [
    {
     "expr": "sum(sum by(bucket) (kv_vb_max_history_disk_size_bytes{cluster_name=~\"$cluster\",bucket=~\"$bucket\",instance=~\"$node\"}))  by (bucket)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "History Logical Disk Size (Bytes)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 7, "x": 14, "y": 119 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(kv_ep_magma_history_logical_disk_size_bytes{cluster_name=~\"$cluster\",bucket=~\"$bucket\",instance=~\"$node\"})  by (bucket)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "History Logical Data Size (Bytes)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 7, "x": 0, "y": 129 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(kv_ep_magma_history_logical_data_size_bytes{cluster_name=~\"$cluster\",bucket=~\"$bucket\",instance=~\"$node\"})  by (bucket)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}