{
 "title": "Magma - Node",
 "tags": [
  "Couchbase",
  "buckets",
  "data",
  "magma"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "30m",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" },
   {
    "name": "cluster",
    "label": "Cluster",
    "query": {
     "query": "label_values(kv_auth_cmds, cluster_name)"
    }
   },
   {
    "name": "node",
    "label": "Node",
    "query": {
     "query": "label_values(kv_auth_cmds{cluster_name=~\"$cluster\"}, instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Gets rate",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (bucket, nodeHostname) (rate(kv_ep_magma_gets{cluster_name=~\"$cluster\",instance=~\"$node\"}[1m]))",
     "legendFormat": "{{bucket}}"
    }
   ]
  },
  {
   "title": "Sets rate",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (bucket, nodeHostname) (rate(kv_ep_magma_sets{cluster_name=~\"$cluster\",instance=~\"$node\"}[1m]))",
     "legendFormat": "{{bucket}}"
    }
   ]
  },
  {
   "title": "Inserts rate",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (bucket, nodeHostname) (rate(kv_ep_magma_inserts{cluster_name=~\"$cluster\",instance=~\"$node\"}[1m]))",
     "legendFormat": "{{bucket}}"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "kv_ep_magma_total_mem_used_bytes{cluster_name=~\"$cluster\",instance=~\"$node\"}",
     "legendFormat": "{{bucket}}"
    }
   ]
  },
  {
   "title": "Thread pool CPU",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (thread_pool, nodeHostname) (rate(kv_thread_cpu_usage_seconds{cluster_name=~\"$cluster\",instance=~\"$node\"}[6m]))",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  { "title": "Disk IO", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 } },
  {
   "title": "Write bytes rate",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (bucket, nodeHostname) (rate(kv_ep_magma_write_bytes_bytes{cluster_name=~\"$cluster\",instance=~\"$node\"}[1m]))",
     "legendFormat": "{{bucket}}"
    }
   ]
  },
  {
   "title": "Write bytes",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (bucket, nodeHostname) (kv_ep_magma_write_bytes_bytes{cluster_name=~\"$cluster\",instance=~\"$node\"})",
     "legendFormat": "{{bucket}}"
    }
   ]
  },
  {
   "title": "Bytes incoming rate",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (bucket, nodeHostname) (rate(kv_ep_magma_bytes_incoming_bytes{cluster_name=~\"$cluster\",instance=~\"$node\"}[1m]))",
     "legendFormat": "{{bucket}}"
    }
   ]
  },
  {
   "title": "Bytes incoming",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (bucket, nodeHostname) (kv_ep_magma_bytes_incoming_bytes{cluster_name=~\"$cluster\",instance=~\"$node\"})",
     "legendFormat": "{{bucket}}"
    }
   ]
  },
  {
   "title": "Read bytes rate",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (bucket, nodeHostname) (rate(kv_ep_magma_read_bytes_bytes{cluster_name=~\"$cluster\",instance=~\"$node\"}[1m]))",
     "legendFormat": "{{bucket}}"
    }
   ]
  },
  {
   "title": "Read bytes",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (bucket, nodeHostname) (kv_ep_magma_read_bytes_bytes{cluster_name=~\"$cluster\",instance=~\"$node\"})",
     "legendFormat": "{{bucket}}"
    }
   ]
  },
  {
   "title": "Bytes outgoing rate",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 55 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (bucket, nodeHostname) (rate(kv_ep_magma_bytes_outgoing_bytes{cluster_name=~\"$cluster\",instance=~\"$node\"}[1m]))",
     "legendFormat": "{{bucket}}"
    }
   ]
  },
  {
   "title": "Bytes outgoing",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 55 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (bucket, nodeHostname) (kv_ep_magma_bytes_outgoing_bytes{cluster_name=~\"$cluster\",instance=~\"$node\"})",
     "legendFormat": "{{bucket}}"
    }
   ]
  },
  { "title": "Size", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 64 } },
  {
   "title": "Data block size uncompressed",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 65 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (bucket, nodeHostname) (kv_ep_magma_data_blocks_uncompressed_size{cluster_name=~\"$cluster\",instance=~\"$node\"})",
     "legendFormat": "{{bucket}}"
    }
   ]
  },
  {
   "title": "Total disk usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 65 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (bucket, nodeHostname) (kv_ep_magma_total_disk_usage_bytes{cluster_name=~\"$cluster\",instance=~\"$node\"})",
     "legendFormat": "{{bucket}}"
    }
   ]
  },
  {
   "title": "Fragmentation%",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 74 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (bucket, nodeHostname) (kv_ep_magma_fragmentation_ratio{cluster_name=~\"$cluster\",instance=~\"$node\"} * 100)",
     "legendFormat": "{{bucket}}"
    }
   ]
  },
  {
   "title": "Data block size compressed",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 74 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (bucket, nodeHostname) (kv_ep_magma_data_blocks_compressed_size{cluster_name=~\"$cluster\",instance=~\"$node\"})",
     "legendFormat": "{{bucket}}"
    }
   ]
  },
  { "title": "History", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 83 } },
  {
   "title": "History bytes evicted due to size",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 84 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (bucket, nodeHostname) (kv_ep_magma_history_size_evicted_bytes{cluster_name=~\"$cluster\",instance=~\"$node\"})",
     "legendFormat": "{{bucket}}"
    }
   ]
  },
  {
   "title": "History bytes evicted due to time",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 84 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (bucket, nodeHostname) (kv_ep_magma_history_time_evicted_bytes{cluster_name=~\"$cluster\",instance=~\"$node\"})",
     "legendFormat": "{{bucket}}"
    }
   ]
  }
 ]
}