{
 "title": "Magma - Cluster",
 "tags": [
  "Couchbase",
  "buckets",
  "data",
  "magma"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "30m",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" },
   {
    "name": "cluster",
    "label": "Cluster",
    "query": {
     "query": "label_values(kv_auth_cmds, cluster_name)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Gets rate",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (instance) (rate(kv_ep_magma_gets{cluster_name=~\"$cluster\"}[1m]))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Sets rate",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (instance) (rate(kv_ep_magma_sets{cluster_name=~\"$cluster\"}[1m]))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Inserts rate",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (instance) (rate(kv_ep_magma_inserts{cluster_name=~\"$cluster\"}[1m]))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (instance) (kv_ep_magma_total_mem_used_bytes{cluster_name=~\"$cluster\"})",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  { "title": "Disk IO", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "Write bytes",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (instance) (kv_ep_magma_write_bytes_bytes{cluster_name=~\"$cluster\"})",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Write bytes rate",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (instance) (rate(kv_ep_magma_write_bytes_bytes{cluster_name=~\"$cluster\"}[1m]))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Bytes incoming",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (instance) (kv_ep_magma_bytes_incoming_bytes{cluster_name=~\"$cluster\"})",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Bytes incoming rate",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (instance) (rate(kv_ep_magma_bytes_incoming_bytes{cluster_name=~\"$cluster\"}[1m]))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Read bytes",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (instance) (kv_ep_magma_read_bytes_bytes{cluster_name=~\"$cluster\"})",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Read bytes rate",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (instance) (rate(kv_ep_magma_read_bytes_bytes{cluster_name=~\"$cluster\"}[1m]))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Bytes outgoing",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (instance) (kv_ep_magma_bytes_outgoing_bytes{cluster_name=~\"$cluster\"})",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Bytes outgoing rate",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (instance) (rate(kv_ep_magma_bytes_outgoing_bytes{cluster_name=~\"$cluster\"}[1m]))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  { "title": "Size", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 55 } },
  {
   "title": "Total disk usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (instance) (kv_ep_magma_total_disk_usage_bytes{cluster_name=~\"$cluster\"})",
     "legendFormat": "{{instance}}"
    }
   ]
  }
 ]
}