{
 "title": "Couchbase Data Service",
 "tags": [
  "couchbase",
  "data",
  "buckets"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "15s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" },
   {
    "name": "bucket",
    "label": "Bucket",
    "query": {
     "query": "label_values(kv_num_vbuckets{cluster_name=~\"$cluster\"}, bucket)"
    }
   },
   {
    "name": "cluster",
    "label": "Cluster",
    "query": {
     "query": "label_values(kv_auth_cmds, cluster_name)"
    }
   },
   {
    "name": "node",
    "label": "Node",
    "query": {
     "query": "label_values(kv_auth_cmds{cluster_name=~\"$cluster\"}, instance)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Disk Read Failures / sec",
   "type": "timeseries",
   "description": "Number of disk write and read failures (measured from ep_data_write_failed  and ep_data_read_failed)",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(increase(kv_ep_data_read_failed{cluster_name=~\"$cluster\",instance=~\"$node\"}[$__rate_interval])) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Commit Failures ",
   "type": "timeseries",
   "description": "Number of times a transaction failed to commit due to storage errors.",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(increase(kv_ep_item_commit_failed{cluster_name=~\"$cluster\",bucket=~\"$bucket\",instance=~\"$node\"}[$__rate_interval])) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Disk Write Failures / sec",
   "type": "timeseries",
   "description": "Number of disk write and read failures",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(increase(kv_ep_data_write_failed{cluster_name=~\"$cluster\",instance=~\"$node\"}[$__rate_interval])) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Temp OOMs",
   "type": "timeseries",
   "description": "Number of times temporary OOMs happened while processing operations.  Number of back-offs sent per second to client SDKs due to \"out of memory\" situations from this bucket.  ",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(increase(kv_ep_tmp_oom_errors{cluster_name=~\"$cluster\",bucket=~\"$bucket\",instance=~\"$node\"}[$__rate_interval])) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Hard OOM Errors",
   "type": "timeseries",
   "description": "Number of times unrecoverable OOMs happened while processing operations.",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(increase(kv_ep_oom_errors{cluster_name=~\"$cluster\",bucket=~\"$bucket\",instance=~\"$node\"}[$__rate_interval])) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Data Read/sec",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum(rate(kv_read_bytes{cluster_name=~\"$cluster\",bucket=~\"$bucket\",instance=~\"$node\"}[$__rate_interval])) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Current Connections",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "kv_curr_connections{cluster_name=~\"$cluster\",instance=~\"$node\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "System Connections",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "kv_system_connections{cluster_name=~\"$cluster\",instance=~\"$node\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Data Written/sec",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum(rate(kv_written_bytes{cluster_name=~\"$cluster\",bucket=~\"$bucket\",instance=~\"$node\"}[$__rate_interval])) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Daemon Connections",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "kv_daemon_connections{cluster_name=~\"$cluster\",instance=~\"$node\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Connection Yields",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(increase(kv_conn_yields{cluster_name=~\"$cluster\",bucket=~\"$bucket\",instance=~\"$node\"}[$__rate_interval])) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Node Resources",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 },
   "collapsed": true,
   "panels": [
    {
     "title": "System Processes",
     "type": "table",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 22 },
     "targets": [
      {
       "expr": "sysproc_cpu_utilization{cluster_name=\"$cluster\",instance=~\"$node\"}"
      },
      {
       "expr": "sysproc_mem_size{cluster_name=\"$cluster\",instance=~\"$node\"}"
      },
      {
       "expr": "sysproc_mem_resident{cluster_name=\"$cluster\",instance=~\"$node\"}"
      },
      {
       "expr": "sysproc_mem_share{cluster_name=\"$cluster\",instance=~\"$node\"}"
      }
     ]
    },
    {
     "title": "CPU Utilization ",
     "type": "timeseries",
     "description": "CPU Utilization per Node.",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 31 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "sys_cpu_host_utilization_rate{cluster_name=~\"$cluster\",instance=~\"$node\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "memcached and projector CPU Usage",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 31 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "((sum by(proc, pod)(sysproc_cpu_utilization{cluster_name=~\"$cluster\",instance=~\"$node\",proc=~\"(memcached|projector).*\"})) / ignoring(proc) group_left sum by(pod) (sys_cpu_host_cores_available{cluster_name=~\"$cluster\",instance=~\"$node\"}) / 100)",
       "legendFormat": "{{proc}} - {{pod}}"
      }
     ]
    },
    {
     "title": "Memory Utilization ",
     "type": "timeseries",
     "description": "Memory Utilization  per Node.",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 38 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "(1 - sys_mem_actual_free{cluster_name=~\"$cluster\",instance=~\"$node\"} / sys_mem_total{cluster_name=~\"$cluster\",instance=~\"$node\"}) * 100",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "memcached and projector Memory Usage",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 38 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "sysproc_mem_resident{instance=~\"$node\",proc=~\"(memcached|projector).*\"}",
       "legendFormat": "{{proc}} - {{instance}}"
      }
     ]
    },
    {
     "title": "Disk Operations",
     "type": "timeseries",
     "description": "The number of bytes read from or written to the device per second.",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 45 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "sum(rate(sys_disk_write_bytes{cluster_name=~\"$cluster\",instance=~\"$node\"}[$__rate_interval])) by (instance, disk)",
       "legendFormat": "Write bytes - {{disk}}"
      },
      {
       "expr": "sum(rate(sys_disk_read_bytes{instance=~\"$node\"}[$__rate_interval])) by (instance, disk)",
       "legendFormat": "Read bytes - {{disk}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Performance - KV Commands",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 },
   "collapsed": true,
   "panels": [
    {
     "title": "GET/sec Heatmap",
     "type": "heatmap",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 60 },
     "targets": [
      {
       "expr": "sum by(le) (rate(kv_cmd_duration_seconds_bucket{cluster_name=~\"$cluster\",bucket=~\"$bucket\",opcode=\"GET\"}[$__rate_interval]))",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "GET/sec - Percentiles",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 60 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.5, avg by (le) (rate(kv_cmd_duration_seconds_bucket{cluster_name=~\"$cluster\",bucket=~\"$bucket\",opcode=\"GET\",instance=~\"$node\"}[$__rate_interval])))",
       "legendFormat": "50th Percentile"
      },
      {
       "expr": "histogram_quantile(0.9, avg by (le) (rate(kv_cmd_duration_seconds_bucket{cluster_name=~\"$cluster\",bucket=~\"$bucket\",opcode=\"GET\",instance=~\"$node\"}[$__rate_interval])))",
       "legendFormat": "90th Percentile"
      },
      {
       "expr": "histogram_quantile(0.95, avg by (le) (rate(kv_cmd_duration_seconds_bucket{cluster_name=~\"$cluster\",bucket=~\"$bucket\",opcode=\"GET\",instance=~\"$node\"}[$__rate_interval])))",
       "legendFormat": "95th Percentile"
      },
      {
       "expr": "histogram_quantile(0.99, avg by (le) (rate(kv_cmd_duration_seconds_bucket{cluster_name=~\"$cluster\",bucket=~\"$bucket\",opcode=\"GET\",instance=~\"$node\"}[$__rate_interval])))",
       "legendFormat": "99th Percentile"
      },
      {
       "expr": "histogram_quantile(0.999, avg by (le) (rate(kv_cmd_duration_seconds_bucket{cluster_name=~\"$cluster\",bucket=~\"$bucket\",opcode=\"GET\",instance=~\"$node\"}[$__rate_interval])))",
       "legendFormat": "99.9th Percentile"
      }
     ]
    },
    {
     "title": "GET/sec - 99th Percentile",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 60 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.99, avg without (instance) (rate(kv_cmd_duration_seconds_bucket{cluster_name=~\"$cluster\",bucket=~\"$bucket\",opcode=\"GET\",instance=~\"$node\"}[$__rate_interval])))",
       "legendFormat": "{{bucket}}"
      }
     ]
    },
    {
     "title": "SET/sec Heatmap",
     "type": "heatmap",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 67 },
     "targets": [
      {
       "expr": "sum by(le) (rate(kv_cmd_duration_seconds_bucket{cluster_name=~\"$cluster\",bucket=~\"$bucket\",opcode=\"SET\"}[$__rate_interval]))",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "SET/sec - Percentiles",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 67 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.5, avg by (le) (rate(kv_cmd_duration_seconds_bucket{cluster_name=~\"$cluster\",bucket=~\"$bucket\",opcode=\"SET\",instance=~\"$node\"}[$__rate_interval])))",
       "legendFormat": "50th Percentile"
      },
      {
       "expr": "histogram_quantile(0.9, avg by (le) (rate(kv_cmd_duration_seconds_bucket{cluster_name=~\"$cluster\",bucket=~\"$bucket\",opcode=\"SET\",instance=~\"$node\"}[$__rate_interval])))",
       "legendFormat": "90th Percentile"
      },
      {
       "expr": "histogram_quantile(0.95, avg by (le) (rate(kv_cmd_duration_seconds_bucket{cluster_name=~\"$cluster\",bucket=~\"$bucket\",opcode=\"SET\",instance=~\"$node\"}[$__rate_interval])))",
       "legendFormat": "95th Percentile"
      },
      {
       "expr": "histogram_quantile(0.99, avg by (le) (rate(kv_cmd_duration_seconds_bucket{cluster_name=~\"$cluster\",bucket=~\"$bucket\",opcode=\"SET\",instance=~\"$node\"}[$__rate_interval])))",
       "legendFormat": "99th Percentile"
      },
      {
       "expr": "histogram_quantile(0.999, avg by (le) (rate(kv_cmd_duration_seconds_bucket{cluster_name=~\"$cluster\",bucket=~\"$bucket\",opcode=\"SET\",instance=~\"$node\"}[$__rate_interval])))",
       "legendFormat": "99.9th Percentile"
      }
     ]
    },
    {
     "title": "SET/sec - 99th Percentile",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 67 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.99, avg without (instance) (rate(kv_cmd_duration_seconds_bucket{cluster_name=~\"$cluster\",bucket=~\"$bucket\",opcode=\"GET\",instance=~\"$node\"}[$__rate_interval])))",
       "legendFormat": "{{bucket}}"
      }
     ]
    },
    {
     "title": "GET_CLUSTER_CONFIG/sec Heatmap",
     "type": "heatmap",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 74 },
     "targets": [
      {
       "expr": "sum by(le) (rate(kv_cmd_duration_seconds_bucket{cluster_name=~\"$cluster\",bucket=~\"$bucket\",opcode=\"GET_CLUSTER_CONFIG\"}[$__rate_interval]))",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "GET_CLUSTER_CONFIG/sec - Percentiles",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 74 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.5, avg by (le) (rate(kv_cmd_duration_seconds_bucket{cluster_name=~\"$cluster\",bucket=~\"$bucket\",opcode=\"GET_CLUSTER_CONFIG\",instance=~\"$node\"}[$__rate_interval])))",
       "legendFormat": "50th Percentile"
      },
      {
       "expr": "histogram_quantile(0.9, avg by (le) (rate(kv_cmd_duration_seconds_bucket{cluster_name=~\"$cluster\",bucket=~\"$bucket\",opcode=\"GET_CLUSTER_CONFIG\",instance=~\"$node\"}[$__rate_interval])))",
       "legendFormat": "90th Percentile"
      },
      {
       "expr": "histogram_quantile(0.95, avg by (le) (rate(kv_cmd_duration_seconds_bucket{cluster_name=~\"$cluster\",bucket=~\"$bucket\",opcode=\"GET_CLUSTER_CONFIG\",instance=~\"$node\"}[$__rate_interval])))",
       "legendFormat": "95th Percentile"
      },
      {
       "expr": "histogram_quantile(0.99, avg by (le) (rate(kv_cmd_duration_seconds_bucket{cluster_name=~\"$cluster\",bucket=~\"$bucket\",opcode=\"GET_CLUSTER_CONFIG\",instance=~\"$node\"}[$__rate_interval])))",
       "legendFormat": "99th Percentile"
      },
      {
       "expr": "histogram_quantile(0.999, avg by (le) (rate(kv_cmd_duration_seconds_bucket{cluster_name=~\"$cluster\",bucket=~\"$bucket\",opcode=\"GET_CLUSTER_CONFIG\",instance=~\"$node\"}[$__rate_interval])))",
       "legendFormat": "99.9th Percentile"
      }
     ]
    },
    {
     "title": "GET_CLUSTER_CONFIG/sec - 99th Percentile",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 74 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.99, avg without (instance) (rate(kv_cmd_duration_seconds_bucket{cluster_name=~\"$cluster\",bucket=~\"$bucket\",opcode=\"GET_CLUSTER_CONFIG\",instance=~\"$node\"}[$__rate_interval])))",
       "legendFormat": "{{bucket}}"
      }
     ]
    },
    {
     "title": "STAT/sec Heatmap",
     "type": "heatmap",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 81 },
     "targets": [
      {
       "expr": "sum by(le) (rate(kv_cmd_duration_seconds_bucket{cluster_name=~\"$cluster\",bucket=~\"$bucket\",opcode=\"STAT\"}[$__rate_interval]))",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "STAT/sec - Percentiles",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 81 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.5, avg by (le) (rate(kv_cmd_duration_seconds_bucket{cluster_name=~\"$cluster\",bucket=~\"$bucket\",opcode=\"STAT\",instance=~\"$node\"}[$__rate_interval])))",
       "legendFormat": "50th Percentile"
      },
      {
       "expr": "histogram_quantile(0.9, avg by (le) (rate(kv_cmd_duration_seconds_bucket{cluster_name=~\"$cluster\",bucket=~\"$bucket\",opcode=\"STAT\",instance=~\"$node\"}[$__rate_interval])))",
       "legendFormat": "90th Percentile"
      },
      {
       "expr": "histogram_quantile(0.95, avg by (le) (rate(kv_cmd_duration_seconds_bucket{cluster_name=~\"$cluster\",bucket=~\"$bucket\",opcode=\"STAT\",instance=~\"$node\"}[$__rate_interval])))",
       "legendFormat": "95th Percentile"
      },
      {
       "expr": "histogram_quantile(0.99, avg by (le) (rate(kv_cmd_duration_seconds_bucket{cluster_name=~\"$cluster\",bucket=~\"$bucket\",opcode=\"STAT\",instance=~\"$node\"}[$__rate_interval])))",
       "legendFormat": "99th Percentile"
      },
      {
       "expr": "histogram_quantile(0.999, avg by (le) (rate(kv_cmd_duration_seconds_bucket{cluster_name=~\"$cluster\",bucket=~\"$bucket\",opcode=\"STAT\",instance=~\"$node\"}[$__rate_interval])))",
       "legendFormat": "99.9th Percentile"
      }
     ]
    },
    {
     "title": "STAT/sec - 99th Percentile",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 81 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.99, avg without (instance) (rate(kv_cmd_duration_seconds_bucket{cluster_name=~\"$cluster\",bucket=~\"$bucket\",opcode=\"STAT\",instance=~\"$node\"}[$__rate_interval])))",
       "legendFormat": "{{bucket}}"
      }
     ]
    },
    {
     "title": "SELECT_BUCKET/sec Heatmap",
     "type": "heatmap",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 88 },
     "targets": [
      {
       "expr": "sum by(le) (rate(kv_cmd_duration_seconds_bucket{cluster_name=~\"$cluster\",bucket=~\"$bucket\",opcode=\"SELECT_BUCKET\"}[$__rate_interval]))",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "SELECT_BUCKET/sec - Percentiles",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 88 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.5, avg by (le) (rate(kv_cmd_duration_seconds_bucket{cluster_name=~\"$cluster\",bucket=~\"$bucket\",opcode=\"SELECT_BUCKET\",instance=~\"$node\"}[$__rate_interval])))",
       "legendFormat": "50th Percentile"
      },
      {
       "expr": "histogram_quantile(0.9, avg by (le) (rate(kv_cmd_duration_seconds_bucket{cluster_name=~\"$cluster\",bucket=~\"$bucket\",opcode=\"SELECT_BUCKET\",instance=~\"$node\"}[$__rate_interval])))",
       "legendFormat": "90th Percentile"
      },
      {
       "expr": "histogram_quantile(0.95, avg by (le) (rate(kv_cmd_duration_seconds_bucket{cluster_name=~\"$cluster\",bucket=~\"$bucket\",opcode=\"SELECT_BUCKET\",instance=~\"$node\"}[$__rate_interval])))",
       "legendFormat": "95th Percentile"
      },
      {
       "expr": "histogram_quantile(0.99, avg by (le) (rate(kv_cmd_duration_seconds_bucket{cluster_name=~\"$cluster\",bucket=~\"$bucket\",opcode=\"SELECT_BUCKET\",instance=~\"$node\"}[$__rate_interval])))",
       "legendFormat": "99th Percentile"
      },
      {
       "expr": "histogram_quantile(0.999, avg by (le) (rate(kv_cmd_duration_seconds_bucket{cluster_name=~\"$cluster\",bucket=~\"$bucket\",opcode=\"SELECT_BUCKET\",instance=~\"$node\"}[$__rate_interval])))",
       "legendFormat": "99.9th Percentile"
      }
     ]
    },
    {
     "title": "SELECT_BUCKET/sec - 99th Percentile",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 88 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.99, avg without (instance) (rate(kv_cmd_duration_seconds_bucket{cluster_name=~\"$cluster\",bucket=~\"$bucket\",opcode=\"SELECT_BUCKET\",instance=~\"$node\"}[$__rate_interval])))",
       "legendFormat": "{{bucket}}"
      }
     ]
    },
    {
     "title": "COLLECTIONS_GET_MANIFEST/sec Heatmap",
     "type": "heatmap",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 95 },
     "targets": [
      {
       "expr": "sum by(le) (rate(kv_cmd_duration_seconds_bucket{cluster_name=~\"$cluster\",bucket=~\"$bucket\",opcode=\"COLLECTIONS_GET_MANIFEST\"}[$__rate_interval]))",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "COLLECTIONS_GET_MANIFEST/sec - Percentiles",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 95 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.5, avg by (le) (rate(kv_cmd_duration_seconds_bucket{cluster_name=~\"$cluster\",bucket=~\"$bucket\",opcode=\"COLLECTIONS_GET_MANIFEST\",instance=~\"$node\"}[$__rate_interval])))",
       "legendFormat": "50th Percentile"
      },
      {
       "expr": "histogram_quantile(0.9, avg by (le) (rate(kv_cmd_duration_seconds_bucket{cluster_name=~\"$cluster\",bucket=~\"$bucket\",opcode=\"COLLECTIONS_GET_MANIFEST\",instance=~\"$node\"}[$__rate_interval])))",
       "legendFormat": "90th Percentile"
      },
      {
       "expr": "histogram_quantile(0.95, avg by (le) (rate(kv_cmd_duration_seconds_bucket{cluster_name=~\"$cluster\",bucket=~\"$bucket\",opcode=\"COLLECTIONS_GET_MANIFEST\",instance=~\"$node\"}[$__rate_interval])))",
       "legendFormat": "95th Percentile"
      },
      {
       "expr": "histogram_quantile(0.99, avg by (le) (rate(kv_cmd_duration_seconds_bucket{cluster_name=~\"$cluster\",bucket=~\"$bucket\",opcode=\"COLLECTIONS_GET_MANIFEST\",instance=~\"$node\"}[$__rate_interval])))",
       "legendFormat": "99th Percentile"
      },
      {
       "expr": "histogram_quantile(0.999, avg by (le) (rate(kv_cmd_duration_seconds_bucket{cluster_name=~\"$cluster\",bucket=~\"$bucket\",opcode=\"COLLECTIONS_GET_MANIFEST\",instance=~\"$node\"}[$__rate_interval])))",
       "legendFormat": "99.9th Percentile"
      }
     ]
    },
    {
     "title": "COLLECTIONS_GET_MANIFEST/sec - 99th Percentile",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 95 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.99, avg without (instance) (rate(kv_cmd_duration_seconds_bucket{cluster_name=~\"$cluster\",bucket=~\"$bucket\",opcode=\"COLLECTIONS_GET_MANIFEST\",instance=~\"$node\"}[$__rate_interval])))",
       "legendFormat": "{{bucket}}"
      }
     ]
    },
    {
     "title": "HELLO Heatmap",
     "type": "heatmap",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 102 },
     "targets": [
      {
       "expr": "sum by(le) (kv_cmd_duration_seconds_bucket{cluster_name=~\"$cluster\",bucket=~\"$bucket\",opcode=\"HELLO\"})",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "HELLO - Percentiles",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 102 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.5, avg by (le) (kv_cmd_duration_seconds_bucket{cluster_name=~\"$cluster\",bucket=~\"$bucket\",opcode=\"HELLO\",instance=~\"$node\"}))",
       "legendFormat": "50th Percentile"
      },
      {
       "expr": "histogram_quantile(0.9, avg by (le) (kv_cmd_duration_seconds_bucket{cluster_name=~\"$cluster\",bucket=~\"$bucket\",opcode=\"HELLO\",instance=~\"$node\"}))",
       "legendFormat": "90th Percentile"
      },
      {
       "expr": "histogram_quantile(0.95, avg by (le) (kv_cmd_duration_seconds_bucket{cluster_name=~\"$cluster\",bucket=~\"$bucket\",opcode=\"HELLO\",instance=~\"$node\"}))",
       "legendFormat": "95th Percentile"
      },
      {
       "expr": "histogram_quantile(0.99, avg by (le) (kv_cmd_duration_seconds_bucket{cluster_name=~\"$cluster\",bucket=~\"$bucket\",opcode=\"HELLO\",instance=~\"$node\"}))",
       "legendFormat": "99th Percentile"
      },
      {
       "expr": "histogram_quantile(0.999, avg by (le) (kv_cmd_duration_seconds_bucket{cluster_name=~\"$cluster\",bucket=~\"$bucket\",opcode=\"HELLO\",instance=~\"$node\"}))",
       "legendFormat": "99.9th Percentile"
      }
     ]
    },
    {
     "title": "HELLO - 99th Percentile",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 102 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.99, avg without (instance) (kv_cmd_duration_seconds_bucket{cluster_name=~\"$cluster\",bucket=~\"$bucket\",opcode=\"HELLO\",instance=~\"$node\"}))",
       "legendFormat": "{{bucket}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Performance - KV Disk",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 },
   "collapsed": true,
   "panels": [
    {
     "title": "Disk Updates/sec Heatmap",
     "type": "heatmap",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 61 },
     "targets": [
      {
       "expr": "sum by(le) (rate(kv_disk_seconds_bucket{cluster_name=~\"$cluster\",bucket=~\"$bucket\",op=\"update\"}[$__rate_interval]))",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "Disk Updates/sec - Percentiles",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 61 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.5, avg by (le) (rate(kv_disk_seconds_bucket{cluster_name=~\"$cluster\",bucket=~\"$bucket\",op=\"update\",instance=~\"$node\"}[$__rate_interval])))",
       "legendFormat": "50th Percentile"
      },
      {
       "expr": "histogram_quantile(0.9, avg by (le) (rate(kv_disk_seconds_bucket{cluster_name=~\"$cluster\",bucket=~\"$bucket\",op=\"update\",instance=~\"$node\"}[$__rate_interval])))",
       "legendFormat": "90th Percentile"
      },
      {
       "expr": "histogram_quantile(0.95, avg by (le) (rate(kv_disk_seconds_bucket{cluster_name=~\"$cluster\",bucket=~\"$bucket\",op=\"update\",instance=~\"$node\"}[$__rate_interval])))",
       "legendFormat": "95th Percentile"
      },
      {
       "expr": "histogram_quantile(0.99, avg by (le) (rate(kv_disk_seconds_bucket{cluster_name=~\"$cluster\",bucket=~\"$bucket\",op=\"update\",instance=~\"$node\"}[$__rate_interval])))",
       "legendFormat": "99th Percentile"
      },
      {
       "expr": "histogram_quantile(0.999, avg by (le) (rate(kv_disk_seconds_bucket{cluster_name=~\"$cluster\",bucket=~\"$bucket\",op=\"update\",instance=~\"$node\"}[$__rate_interval])))",
       "legendFormat": "99.9th Percentile"
      }
     ]
    },
    {
     "title": "Disk Updates/sec - 99th Percentile",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 61 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.99, avg without (instance) (rate(kv_disk_seconds_bucket{cluster_name=~\"$cluster\",bucket=~\"$bucket\",op=\"update\",instance=~\"$node\"}[$__rate_interval])))",
       "legendFormat": "{{bucket}}"
      }
     ]
    },
    {
     "title": "Disk Commits/sec Heatmap",
     "type": "heatmap",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 68 },
     "targets": [
      {
       "expr": "sum by(le) (rate(kv_disk_seconds_bucket{cluster_name=~\"$cluster\",bucket=~\"$bucket\",op=\"commit\"}[$__rate_interval]))",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "Disk Commits/sec - Percentiles",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 68 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.5, avg by (le) (rate(kv_disk_seconds_bucket{cluster_name=~\"$cluster\",bucket=~\"$bucket\",op=\"commit\",instance=~\"$node\"}[$__rate_interval])))",
       "legendFormat": "50th Percentile"
      },
      {
       "expr": "histogram_quantile(0.9, avg by (le) (rate(kv_disk_seconds_bucket{cluster_name=~\"$cluster\",bucket=~\"$bucket\",op=\"commit\",instance=~\"$node\"}[$__rate_interval])))",
       "legendFormat": "90th Percentile"
      },
      {
       "expr": "histogram_quantile(0.95, avg by (le) (rate(kv_disk_seconds_bucket{cluster_name=~\"$cluster\",bucket=~\"$bucket\",op=\"commit\",instance=~\"$node\"}[$__rate_interval])))",
       "legendFormat": "95th Percentile"
      },
      {
       "expr": "histogram_quantile(0.99, avg by (le) (rate(kv_disk_seconds_bucket{cluster_name=~\"$cluster\",bucket=~\"$bucket\",op=\"commit\",instance=~\"$node\"}[$__rate_interval])))",
       "legendFormat": "99th Percentile"
      },
      {
       "expr": "histogram_quantile(0.999, avg by (le) (rate(kv_disk_seconds_bucket{cluster_name=~\"$cluster\",bucket=~\"$bucket\",op=\"commit\",instance=~\"$node\"}[$__rate_interval])))",
       "legendFormat": "99.9th Percentile"
      }
     ]
    },
    {
     "title": "Disk Commits/sec - 99th Percentile",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 68 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.99, avg without (instance) (rate(kv_disk_seconds_bucket{cluster_name=~\"$cluster\",bucket=~\"$bucket\",op=\"commit\",instance=~\"$node\"}[$__rate_interval])))",
       "legendFormat": "{{bucket}}"
      }
     ]
    },
    {
     "title": "Disk Inserts/sec Heatmap",
     "type": "heatmap",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 75 },
     "targets": [
      {
       "expr": "sum by(le) (rate(kv_disk_seconds_bucket{cluster_name=~\"$cluster\",bucket=~\"$bucket\",op=\"insert\"}[$__rate_interval]))",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "Disk Inserts/sec - Percentiles",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 75 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.5, avg by (le) (rate(kv_disk_seconds_bucket{cluster_name=~\"$cluster\",bucket=~\"$bucket\",op=\"insert\",instance=~\"$node\"}[$__rate_interval])))",
       "legendFormat": "50th Percentile"
      },
      {
       "expr": "histogram_quantile(0.9, avg by (le) (rate(kv_disk_seconds_bucket{cluster_name=~\"$cluster\",bucket=~\"$bucket\",op=\"insert\",instance=~\"$node\"}[$__rate_interval])))",
       "legendFormat": "90th Percentile"
      },
      {
       "expr": "histogram_quantile(0.95, avg by (le) (rate(kv_disk_seconds_bucket{cluster_name=~\"$cluster\",bucket=~\"$bucket\",op=\"insert\",instance=~\"$node\"}[$__rate_interval])))",
       "legendFormat": "95th Percentile"
      },
      {
       "expr": "histogram_quantile(0.99, avg by (le) (rate(kv_disk_seconds_bucket{cluster_name=~\"$cluster\",bucket=~\"$bucket\",op=\"insert\",instance=~\"$node\"}[$__rate_interval])))",
       "legendFormat": "99th Percentile"
      },
      {
       "expr": "histogram_quantile(0.999, avg by (le) (rate(kv_disk_seconds_bucket{cluster_name=~\"$cluster\",bucket=~\"$bucket\",op=\"insert\",instance=~\"$node\"}[$__rate_interval])))",
       "legendFormat": "99.9th Percentile"
      }
     ]
    },
    {
     "title": "Disk Inserts/sec - 99th Percentile",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 75 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.99, avg without (instance) (rate(kv_disk_seconds_bucket{cluster_name=~\"$cluster\",bucket=~\"$bucket\",op=\"insert\",instance=~\"$node\"}[$__rate_interval])))",
       "legendFormat": "{{bucket}}"
      }
     ]
    },
    {
     "title": "Disk Deletes/sec Heatmap",
     "type": "heatmap",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 82 },
     "targets": [
      {
       "expr": "sum by(le) (rate(kv_disk_seconds_bucket{cluster_name=~\"$cluster\",bucket=~\"$bucket\",op=\"del\"}[$__rate_interval]))",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "Disk Deletes/sec - Percentiles",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 82 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.5, avg by (le) (rate(kv_disk_seconds_bucket{cluster_name=~\"$cluster\",bucket=~\"$bucket\",op=\"del\",instance=~\"$node\"}[$__rate_interval])))",
       "legendFormat": "50th Percentile"
      },
      {
       "expr": "histogram_quantile(0.9, avg by (le) (rate(kv_disk_seconds_bucket{cluster_name=~\"$cluster\",bucket=~\"$bucket\",op=\"del\",instance=~\"$node\"}[$__rate_interval])))",
       "legendFormat": "90th Percentile"
      },
      {
       "expr": "histogram_quantile(0.95, avg by (le) (rate(kv_disk_seconds_bucket{cluster_name=~\"$cluster\",bucket=~\"$bucket\",op=\"del\",instance=~\"$node\"}[$__rate_interval])))",
       "legendFormat": "95th Percentile"
      },
      {
       "expr": "histogram_quantile(0.99, avg by (le) (rate(kv_disk_seconds_bucket{cluster_name=~\"$cluster\",bucket=~\"$bucket\",op=\"del\",instance=~\"$node\"}[$__rate_interval])))",
       "legendFormat": "99th Percentile"
      },
      {
       "expr": "histogram_quantile(0.999, avg by (le) (rate(kv_disk_seconds_bucket{cluster_name=~\"$cluster\",bucket=~\"$bucket\",op=\"del\",instance=~\"$node\"}[$__rate_interval])))",
       "legendFormat": "99.9th Percentile"
      }
     ]
    },
    {
     "title": "Disk Deletes - 99th Percentile",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 82 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.99, avg without (instance) (rate(kv_disk_seconds_bucket{cluster_name=~\"$cluster\",bucket=~\"$bucket\",op=\"del\",instance=~\"$node\"}[$__rate_interval])))",
       "legendFormat": "{{bucket}}"
      }
     ]
    },
    {
     "title": "Disk vBucket Deletes Heatmap",
     "type": "heatmap",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 89 },
     "targets": [
      {
       "expr": "sum by(le) (kv_disk_seconds_bucket{cluster_name=~\"$cluster\",bucket=~\"$bucket\",op=\"vb_del\"})",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "Disk vBucket Deletes - Percentiles",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 89 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.5, avg by (le) (kv_disk_seconds_bucket{cluster_name=~\"$cluster\",bucket=~\"$bucket\",op=\"vb_del\",instance=~\"$node\"}))",
       "legendFormat": "50th Percentile"
      },
      {
       "expr": "histogram_quantile(0.9, avg by (le) (kv_disk_seconds_bucket{cluster_name=~\"$cluster\",bucket=~\"$bucket\",op=\"vb_del\",instance=~\"$node\"}))",
       "legendFormat": "90th Percentile"
      },
      {
       "expr": "histogram_quantile(0.95, avg by (le) (kv_disk_seconds_bucket{cluster_name=~\"$cluster\",bucket=~\"$bucket\",op=\"vb_del\",instance=~\"$node\"}))",
       "legendFormat": "95th Percentile"
      },
      {
       "expr": "histogram_quantile(0.99, avg by (le) (kv_disk_seconds_bucket{cluster_name=~\"$cluster\",bucket=~\"$bucket\",op=\"vb_del\",instance=~\"$node\"}))",
       "legendFormat": "99th Percentile"
      },
      {
       "expr": "histogram_quantile(0.999, avg by (le) (kv_disk_seconds_bucket{cluster_name=~\"$cluster\",bucket=~\"$bucket\",op=\"vb_del\",instance=~\"$node\"}))",
       "legendFormat": "99.9th Percentile"
      }
     ]
    },
    {
     "title": "Disk vBucket Deletes - 99th Percentile",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 89 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.99, avg without (instance) (kv_disk_seconds_bucket{cluster_name=~\"$cluster\",bucket=~\"$bucket\",op=\"vb_del\",instance=~\"$node\"}))",
       "legendFormat": "{{bucket}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Performance - KV Sync",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 },
   "collapsed": true,
   "panels": [
    {
     "title": "majority_and_persist_on_master - Heatmap",
     "type": "heatmap",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 62 },
     "targets": [
      {
       "expr": "sum by(le) (kv_sync_write_commit_duration_seconds_bucket{cluster_name=~\"$cluster\",bucket=~\"$bucket\",instance=~\"$node\",level=\"majority_and_persist_on_master\"})",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "majority_and_persist_on_master - Percentiles",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 62 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.5, avg by (le) (kv_sync_write_commit_duration_seconds_bucket{cluster_name=~\"$cluster\",bucket=~\"$bucket\",instance=~\"$node\",level=\"majority_and_persist_on_master\"}))",
       "legendFormat": "50th Percentile"
      },
      {
       "expr": "histogram_quantile(0.9, avg by (le) (kv_sync_write_commit_duration_seconds_bucket{cluster_name=~\"$cluster\",bucket=~\"$bucket\",instance=~\"$node\",level=\"majority_and_persist_on_master\"}))",
       "legendFormat": "90th Percentile"
      },
      {
       "expr": "histogram_quantile(0.95, avg by (le) (kv_sync_write_commit_duration_seconds_bucket{cluster_name=~\"$cluster\",bucket=~\"$bucket\",instance=~\"$node\",level=\"majority_and_persist_on_master\"}))",
       "legendFormat": "95th Percentile"
      },
      {
       "expr": "histogram_quantile(0.99, avg by (le) (kv_sync_write_commit_duration_seconds_bucket{cluster_name=~\"$cluster\",bucket=~\"$bucket\",instance=~\"$node\",level=\"majority_and_persist_on_master\"}))",
       "legendFormat": "99th Percentile"
      },
      {
       "expr": "histogram_quantile(0.999, avg by (le) (kv_sync_write_commit_duration_seconds_bucket{cluster_name=~\"$cluster\",bucket=~\"$bucket\",instance=~\"$node\",level=\"majority_and_persist_on_master\"}))",
       "legendFormat": "99.9th Percentile"
      }
     ]
    },
    {
     "title": "majority_and_persist_on_master - 99th Percentile",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 62 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.99, avg without (instance) (kv_sync_write_commit_duration_seconds_bucket{cluster_name=~\"$cluster\",bucket=~\"$bucket\",instance=~\"$node\",level=\"majority_and_persist_on_master\"}))",
       "legendFormat": "{{bucket}}"
      }
     ]
    },
    {
     "title": "majority Heatmap",
     "type": "heatmap",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 69 },
     "targets": [
      {
       "expr": "sum by(le) (kv_sync_write_commit_duration_seconds_bucket{cluster_name=~\"$cluster\",bucket=~\"$bucket\",level=\"majority\"})",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "majority - Percentiles",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 69 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.5, avg by (le) (kv_sync_write_commit_duration_seconds_bucket{cluster_name=~\"$cluster\",bucket=~\"$bucket\",instance=~\"$node\",level=\"majority\"}))",
       "legendFormat": "50th Percentile"
      },
      {
       "expr": "histogram_quantile(0.9, avg by (le) (kv_sync_write_commit_duration_seconds_bucket{cluster_name=~\"$cluster\",bucket=~\"$bucket\",instance=~\"$node\",level=\"majority\"}))",
       "legendFormat": "90th Percentile"
      },
      {
       "expr": "histogram_quantile(0.95, avg by (le) (kv_sync_write_commit_duration_seconds_bucket{cluster_name=~\"$cluster\",bucket=~\"$bucket\",instance=~\"$node\",level=\"majority\"}))",
       "legendFormat": "95th Percentile"
      },
      {
       "expr": "histogram_quantile(0.99, avg by (le) (kv_sync_write_commit_duration_seconds_bucket{cluster_name=~\"$cluster\",bucket=~\"$bucket\",instance=~\"$node\",level=\"majority\"}))",
       "legendFormat": "99th Percentile"
      },
      {
       "expr": "histogram_quantile(0.999, avg by (le) (kv_sync_write_commit_duration_seconds_bucket{cluster_name=~\"$cluster\",bucket=~\"$bucket\",instance=~\"$node\",level=\"majority\"}))",
       "legendFormat": "99.9th Percentile"
      }
     ]
    },
    {
     "title": "majority- 99th Percentile",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 69 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.99, avg without (instance) (kv_sync_write_commit_duration_seconds_bucket{cluster_name=~\"$cluster\",bucket=~\"$bucket\",instance=~\"$node\",level=\"majority\"}))",
       "legendFormat": "{{bucket}}"
      }
     ]
    },
    {
     "title": "persist_to_majority/sec Heatmap",
     "type": "heatmap",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 76 },
     "targets": [
      {
       "expr": "sum by(le) (kv_sync_write_commit_duration_seconds_bucket{cluster_name=~\"$cluster\",bucket=~\"$bucket\",level=\"persist_to_majority\"})",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "majority_and_persist_on_master - Percentiles",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 76 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.5, avg by (le) (kv_sync_write_commit_duration_seconds_bucket{cluster_name=~\"$cluster\",bucket=~\"$bucket\",instance=~\"$node\",level=\"majority_and_persist_on_master\"}))",
       "legendFormat": "50th Percentile"
      },
      {
       "expr": "histogram_quantile(0.9, avg by (le) (kv_sync_write_commit_duration_seconds_bucket{cluster_name=~\"$cluster\",bucket=~\"$bucket\",instance=~\"$node\",level=\"majority_and_persist_on_master\"}))",
       "legendFormat": "90th Percentile"
      },
      {
       "expr": "histogram_quantile(0.95, avg by (le) (kv_sync_write_commit_duration_seconds_bucket{cluster_name=~\"$cluster\",bucket=~\"$bucket\",instance=~\"$node\",level=\"majority_and_persist_on_master\"}))",
       "legendFormat": "95th Percentile"
      },
      {
       "expr": "histogram_quantile(0.99, avg by (le) (kv_sync_write_commit_duration_seconds_bucket{cluster_name=~\"$cluster\",bucket=~\"$bucket\",instance=~\"$node\",level=\"majority_and_persist_on_master\"}))",
       "legendFormat": "99th Percentile"
      },
      {
       "expr": "histogram_quantile(0.999, avg by (le) (kv_sync_write_commit_duration_seconds_bucket{cluster_name=~\"$cluster\",bucket=~\"$bucket\",instance=~\"$node\",level=\"majority_and_persist_on_master\"}))",
       "legendFormat": "99.9th Percentile"
      }
     ]
    },
    {
     "title": "majority_and_persist_on_master - 99th Percentile",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 76 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.99, avg without (instance) (kv_sync_write_commit_duration_seconds_bucket{cluster_name=~\"$cluster\",bucket=~\"$bucket\",instance=~\"$node\",level=\"majority_and_persist_on_master\"}))",
       "legendFormat": "{{bucket}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Background Load",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 },
   "collapsed": true,
   "panels": [
    {
     "title": "Background Load Heatmap",
     "type": "heatmap",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 63 },
     "targets": [
      {
       "expr": "sum by(le) (kv_bg_load_seconds_bucket{cluster_name=~\"$cluster\",bucket=~\"$bucket\"})",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "Background Load - Percentiles",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 63 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.5, avg by (le) (kv_bg_load_seconds_bucket{cluster_name=~\"$cluster\",bucket=~\"$bucket\",instance=~\"$node\"}))",
       "legendFormat": "50th Percentile"
      },
      {
       "expr": "histogram_quantile(0.9, avg by (le) (kv_bg_load_seconds_bucket{cluster_name=~\"$cluster\",bucket=~\"$bucket\",instance=~\"$node\"}))",
       "legendFormat": "90th Percentile"
      },
      {
       "expr": "histogram_quantile(0.95, avg by (le) (kv_bg_load_seconds_bucket{cluster_name=~\"$cluster\",bucket=~\"$bucket\",instance=~\"$node\"}))",
       "legendFormat": "95th Percentile"
      },
      {
       "expr": "histogram_quantile(0.99, avg by (le) (kv_bg_load_seconds_bucket{cluster_name=~\"$cluster\",bucket=~\"$bucket\",instance=~\"$node\"}))",
       "legendFormat": "99th Percentile"
      },
      {
       "expr": "histogram_quantile(0.999, avg by (le) (kv_cmd_duration_seconds_bucket{cluster_name=~\"$cluster\",bucket=~\"$bucket\",instance=~\"$node\"}))",
       "legendFormat": "99.9th Percentile"
      }
     ]
    },
    {
     "title": "Background Load - 99th Percentile",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 63 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.99, avg without (instance) (kv_bg_load_seconds_bucket{cluster_name=~\"$cluster\",bucket=~\"$bucket\",instance=~\"$node\"}))",
       "legendFormat": "{{bucket}}"
      }
     ]
    },
    {
     "title": "Background Wait Heatmap",
     "type": "heatmap",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 70 },
     "targets": [
      {
       "expr": "sum by(le) (kv_bg_wait_seconds_bucket{cluster_name=~\"$cluster\",bucket=~\"$bucket\"})",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "Background Wait - Percentiles",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 70 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.5, avg by (le) (kv_bg_wait_seconds_bucket{cluster_name=~\"$cluster\",bucket=~\"$bucket\",instance=~\"$node\"}))",
       "legendFormat": "50th Percentile"
      },
      {
       "expr": "histogram_quantile(0.9, avg by (le) (kv_bg_wait_seconds_bucket{cluster_name=~\"$cluster\",bucket=~\"$bucket\",instance=~\"$node\"}))",
       "legendFormat": "90th Percentile"
      },
      {
       "expr": "histogram_quantile(0.95, avg by (le) (kv_bg_wait_seconds_bucket{cluster_name=~\"$cluster\",bucket=~\"$bucket\",instance=~\"$node\"}))",
       "legendFormat": "95th Percentile"
      },
      {
       "expr": "histogram_quantile(0.99, avg by (le) (kv_bg_wait_seconds_bucket{cluster_name=~\"$cluster\",bucket=~\"$bucket\",instance=~\"$node\"}))",
       "legendFormat": "99th Percentile"
      },
      {
       "expr": "histogram_quantile(0.999, avg by (le) (kv_bg_wait_seconds_bucket{cluster_name=~\"$cluster\",bucket=~\"$bucket\",instance=~\"$node\"}))",
       "legendFormat": "99.9th Percentile"
      }
     ]
    },
    {
     "title": "GET - 99th Percentile",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 70 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.99, avg without (instance) (kv_cmd_duration_seconds_bucket{cluster_name=~\"$cluster\",bucket=~\"$bucket\",opcode=\"GET\",instance=~\"$node\"}))",
       "legendFormat": "{{bucket}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Warmup",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 },
   "collapsed": true,
   "panels": [
    {
     "title": "Warmup Time by Bucket",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 64 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "sum without (instance) (rate(kv_ep_warmup_time_seconds{cluster_name=~\"$cluster\",bucket=~\"$bucket\"}[$__rate_interval]))",
       "legendFormat": "{{bucket}}"
      }
     ]
    },
    {
     "title": "Warmup Time by Node",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 64 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "sum without (bucket) (rate(kv_ep_warmup_time_seconds{cluster_name=~\"$cluster\",bucket=~\"$bucket\"}[$__rate_interval]))",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Warmup Duplicates by Node",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 64 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum without (bucket) (increase(kv_ep_warmup_dups{cluster_name=~\"$cluster\",bucket=~\"$bucket\"}[$__rate_interval]))",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Warmup Duplicates by Bucket",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 70 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum without (instance) (increase(kv_ep_warmup_dups{cluster_name=~\"$cluster\",bucket=~\"$bucket\"}[$__rate_interval]))",
       "legendFormat": "{{bucket}}"
      }
     ]
    },
    {
     "title": "Warmup OOMs by Bucket",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 70 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum without (instance) (increase(kv_ep_warmup_oom{cluster_name=~\"$cluster\",bucket=~\"$bucket\"}[$__rate_interval]))",
       "legendFormat": "{{bucket}}"
      }
     ]
    },
    {
     "title": "Warmup OOMs by Node",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 70 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum without (bucket) (increase(kv_ep_warmup_oom{cluster_name=~\"$cluster\",bucket=~\"$bucket\"}[$__rate_interval]))",
       "legendFormat": "{{instance}}"
      }
     ]
    }
   ]
  }
 ]
}