{
 "title": "Couchbase vBuckets",
 "tags": [
  "Couchbase",
  "Data",
  "Buckets"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" },
   {
    "name": "cluster",
    "label": "Cluster",
    "query": {
     "query": "label_values(kv_auth_cmds, cluster_name)"
    }
   },
   {
    "name": "bucket",
    "label": "Bucket",
    "query": {
     "query": "label_values(kv_num_vbuckets{cluster_name=~\"$cluster\"}, bucket)"
    }
   },
   {
    "name": "node",
    "label": "Node",
    "query": {
     "query": "label_values(kv_auth_cmds{cluster_name=~\"$cluster\"}, instance)"
    }
   }
  ]
 },
 "panels": [
  { "title": "vBucket Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Active vBuckets Online",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(\n    avg(kv_ep_max_vbuckets{cluster_name=~\"$cluster\",bucket=~\"$bucket\",instance=~\"$node\"})\n    -\n    (\n        sum(kv_num_vbuckets{cluster_name=~\"$cluster\",bucket=~\"$bucket\",instance=~\"$node\",state=~\"active\"})\n        %\n        avg(kv_ep_max_vbuckets{cluster_name=~\"$cluster\",bucket=~\"$bucket\",instance=~\"$node\"})\n    )\n)\n/\navg(kv_ep_max_vbuckets{cluster_name=~\"$cluster\",bucket=~\"$bucket\",instance=~\"$node\"})"
    }
   ]
  },
  {
   "title": "Replica vBuckets Online",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(\n    avg(kv_ep_max_vbuckets{cluster_name=~\"$cluster\",bucket=~\"$bucket\",instance=~\"$node\"})\n    -\n    (\n        sum(kv_num_vbuckets{cluster_name=~\"$cluster\",bucket=~\"$bucket\",state=~\"replica\",instance=~\"$node\"})\n        %\n        avg(kv_ep_max_vbuckets{cluster_name=~\"$cluster\",bucket=~\"$bucket\",instance=~\"$node\"})\n    )\n)\n/\navg(kv_ep_max_vbuckets{cluster_name=~\"$cluster\",bucket=~\"$bucket\",instance=~\"$node\"})"
    }
   ]
  },
  {
   "title": "Pending vBuckets",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kv_num_vbuckets{cluster_name=~\"$cluster\",bucket=~\"$bucket\",state=~\"pending\",instance=~\"$node\"})"
    }
   ]
  },
  {
   "title": "Dead vBuckets",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kv_num_vbuckets{cluster_name=~\"$cluster\",bucket=~\"$bucket\",state=~\"dead\",instance=~\"$node\"})"
    }
   ]
  },
  {
   "title": "Not My vBucket Requests / sec",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum without(instance) (rate(kv_ep_num_not_my_vbuckets{cluster_name=~\"$cluster\",bucket=~\"$bucket\",instance=~\"$node\"}[$__rate_interval]))",
     "legendFormat": "{{bucket}}"
    }
   ]
  },
  {
   "title": "vBucket (Active) Current Items",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum without(instance) (kv_vb_curr_items{cluster_name=~\"$cluster\",bucket=~\"$bucket\",state=\"active\",instance=~\"$node\"})",
     "legendFormat": "{{bucket}}"
    }
   ]
  },
  {
   "title": "vBucket (Replica) Current Items",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum without(instance) (kv_vb_curr_items{cluster_name=~\"$cluster\",bucket=~\"$bucket\",state=\"replica\",instance=~\"$node\"})",
     "legendFormat": "{{bucket}}"
    }
   ]
  },
  {
   "title": "vBucket (Pending) Current Items",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum without(instance) (kv_vb_curr_items{cluster_name=~\"$cluster\",bucket=~\"$bucket\",state=\"pending\",instance=~\"$node\"})",
     "legendFormat": "{{bucket}}"
    }
   ]
  },
  {
   "title": "vBucket (Active) Non-Resident Items",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum without(instance) (kv_vb_num_non_resident{cluster_name=~\"$cluster\",bucket=~\"$bucket\",state=\"active\",instance=~\"$node\"})",
     "legendFormat": "{{bucket}}"
    }
   ]
  },
  {
   "title": "vBucket (Replica) Non-Resident Items",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum without(instance) (kv_vb_num_non_resident{cluster_name=~\"$cluster\",bucket=~\"$bucket\",state=\"replica\",instance=~\"$node\"})",
     "legendFormat": "{{bucket}}"
    }
   ]
  },
  {
   "title": "vBucket (Pending) Non-Resident Items",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum without(instance) (kv_vb_num_non_resident{cluster_name=~\"$cluster\",bucket=~\"$bucket\",state=\"pending\",instance=~\"$node\"})",
     "legendFormat": "{{bucket}}"
    }
   ]
  },
  {
   "title": "vBucket (Active) Memory Resident",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "avg without(instance) (kv_vb_perc_mem_resident_ratio{cluster_name=~\"$cluster\",bucket=~\"$bucket\",state=\"active\",instance=~\"$node\"})",
     "legendFormat": "{{bucket}}"
    }
   ]
  },
  {
   "title": "vBucket (Replica) Memory Resident",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "avg without(instance) (kv_vb_perc_mem_resident_ratio{cluster_name=~\"$cluster\",bucket=~\"$bucket\",state=\"replica\",instance=~\"$node\"})",
     "legendFormat": "{{bucket}}"
    }
   ]
  },
  {
   "title": "vBucket (Pending) Memory Resident",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "avg without(instance) (kv_vb_perc_mem_resident_ratio{cluster_name=~\"$cluster\",bucket=~\"$bucket\",state=\"pending\",instance=~\"$node\"})",
     "legendFormat": "{{bucket}}"
    }
   ]
  },
  {
   "title": "vBucket (Active) Hashtable Size",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum without(instance) (kv_vb_ht_memory_bytes{cluster_name=~\"$cluster\",bucket=~\"$bucket\",state=\"active\",instance=~\"$node\"})",
     "legendFormat": "{{bucket}}"
    }
   ]
  },
  {
   "title": "vBucket (Replica) Hashtable Size",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum without(instance) (kv_vb_ht_memory_bytes{cluster_name=~\"$cluster\",bucket=~\"$bucket\",state=\"replica\",instance=~\"$node\"})",
     "legendFormat": "{{bucket}}"
    }
   ]
  },
  {
   "title": "vBucket (Pending) Hashtable Size",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum without(instance) (kv_vb_ht_memory_bytes{cluster_name=~\"$cluster\",bucket=~\"$bucket\",state=\"pending\",instance=~\"$node\"})",
     "legendFormat": "{{bucket}}"
    }
   ]
  },
  {
   "title": "vBucket Ops",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 },
   "collapsed": true,
   "panels": [
    {
     "title": "vBucket (Active) Create Ops / sec",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 32 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "sum without(instance) (rate(kv_vb_ops_create{cluster_name=~\"$cluster\",bucket=~\"$bucket\",state=\"active\",instance=~\"$node\"}[$__rate_interval]))",
       "legendFormat": "{{bucket}}"
      }
     ]
    },
    {
     "title": "vBucket (Replica) Create Ops / sec",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 32 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "sum without(instance) (rate(kv_vb_ops_create{cluster_name=~\"$cluster\",bucket=~\"$bucket\",state=\"replica\",instance=~\"$node\"}[$__rate_interval]))",
       "legendFormat": "{{bucket}}"
      }
     ]
    },
    {
     "title": "vBucket (Pending) Create Ops / sec",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 32 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "sum without(instance) (rate(kv_vb_ops_create{cluster_name=~\"$cluster\",bucket=~\"$bucket\",state=\"pending\",instance=~\"$node\"}[$__rate_interval]))",
       "legendFormat": "{{bucket}}"
      }
     ]
    },
    {
     "title": "vBucket (Active) Delete Ops / sec",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 38 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "sum without(instance) (rate(kv_vb_ops_delete{cluster_name=~\"$cluster\",bucket=~\"$bucket\",state=\"active\",instance=~\"$node\"}[$__rate_interval]))",
       "legendFormat": "{{bucket}}"
      }
     ]
    },
    {
     "title": "vBucket (Replica) Delete Ops / sec",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 38 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "sum without(instance) (rate(kv_vb_ops_delete{cluster_name=~\"$cluster\",bucket=~\"$bucket\",state=\"replica\",instance=~\"$node\"}[$__rate_interval]))",
       "legendFormat": "{{bucket}}"
      }
     ]
    },
    {
     "title": "vBucket (Pending) Delete Ops / sec",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 38 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "sum without(instance) (rate(kv_vb_ops_delete{cluster_name=~\"$cluster\",bucket=~\"$bucket\",state=\"pending\",instance=~\"$node\"}[$__rate_interval]))",
       "legendFormat": "{{bucket}}"
      }
     ]
    },
    {
     "title": "vBucket (Active) Get Ops / sec",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 44 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "sum without(instance) (rate(kv_vb_ops_get{cluster_name=~\"$cluster\",bucket=~\"$bucket\",state=\"active\",instance=~\"$node\"}[$__rate_interval]))",
       "legendFormat": "{{bucket}}"
      }
     ]
    },
    {
     "title": "vBucket (Replica) Get Ops / sec",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 44 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "sum without(instance) (rate(kv_vb_ops_get{cluster_name=~\"$cluster\",bucket=~\"$bucket\",state=\"replica\",instance=~\"$node\"}[$__rate_interval]))",
       "legendFormat": "{{bucket}}"
      }
     ]
    },
    {
     "title": "vBucket (Pending) Get Ops / sec",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 44 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "sum without(instance) (rate(kv_vb_ops_get{cluster_name=~\"$cluster\",bucket=~\"$bucket\",state=\"pending\",instance=~\"$node\"}[$__rate_interval]))",
       "legendFormat": "{{bucket}}"
      }
     ]
    },
    {
     "title": "vBucket (Active) Update Ops / sec",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 50 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "sum without(instance) (rate(kv_vb_ops_update{cluster_name=~\"$cluster\",bucket=~\"$bucket\",state=\"active\",instance=~\"$node\"}[$__rate_interval]))",
       "legendFormat": "{{bucket}}"
      }
     ]
    },
    {
     "title": "vBucket (Replica) Update Ops / sec",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 50 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "sum without(instance) (rate(kv_vb_ops_update{cluster_name=~\"$cluster\",bucket=~\"$bucket\",state=\"replica\",instance=~\"$node\"}[$__rate_interval]))",
       "legendFormat": "{{bucket}}"
      }
     ]
    },
    {
     "title": "vBucket (Pending) Update Ops / sec",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 50 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "sum without(instance) (rate(kv_vb_ops_update{cluster_name=~\"$cluster\",bucket=~\"$bucket\",state=\"pending\",instance=~\"$node\"}[$__rate_interval]))",
       "legendFormat": "{{bucket}}"
      }
     ]
    },
    {
     "title": "vBucket (Active) Ejects / sec",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 56 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "sum without(instance) (rate(kv_vb_eject{cluster_name=~\"$cluster\",bucket=~\"$bucket\",state=\"active\",instance=~\"$node\"}[$__rate_interval]))",
       "legendFormat": "{{bucket}}"
      }
     ]
    },
    {
     "title": "vBucket (Replica) Ejects / sec",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 56 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "sum without(instance) (rate(kv_vb_eject{cluster_name=~\"$cluster\",bucket=~\"$bucket\",state=\"replica\",instance=~\"$node\"}[$__rate_interval]))",
       "legendFormat": "{{bucket}}"
      }
     ]
    },
    {
     "title": "vBucket (Pending) Ejects / sec",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 56 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "sum without(instance) (kv_vb_eject{cluster_name=~\"$cluster\",bucket=~\"$bucket\",state=\"pending\",instance=~\"$node\"})",
       "legendFormat": "{{bucket}}"
      }
     ]
    },
    {
     "title": "vBucket (Active) Expiries / sec",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 62 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "sum without(instance) (rate(kv_vb_expired{cluster_name=~\"$cluster\",bucket=~\"$bucket\",state=\"active\",instance=~\"$node\"}[$__rate_interval]))",
       "legendFormat": "{{bucket}}"
      }
     ]
    },
    {
     "title": "vBucket (Replica) Expiries / sec",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 62 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "sum without(instance) (rate(kv_vb_expired{cluster_name=~\"$cluster\",bucket=~\"$bucket\",state=\"replica\",instance=~\"$node\"}[$__rate_interval]))",
       "legendFormat": "{{bucket}}"
      }
     ]
    },
    {
     "title": "vBucket (Pending) Expiries / sec",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 62 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "sum without(instance) (rate(kv_vb_eject{cluster_name=~\"$cluster\",bucket=~\"$bucket\",state=\"pending\",instance=~\"$node\"}[$__rate_interval]))",
       "legendFormat": "{{bucket}}"
      }
     ]
    },
    {
     "title": "vBucket (Active) Rejected Ops / sec",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 68 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "sum without(instance) (rate(kv_vb_ops_reject{cluster_name=~\"$cluster\",bucket=~\"$bucket\",state=\"active\",instance=~\"$node\"}[$__rate_interval]))",
       "legendFormat": "{{bucket}}"
      }
     ]
    },
    {
     "title": "vBucket (Replica) Rejected Ops / sec",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 68 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "sum without(instance) (rate(kv_vb_ops_reject{cluster_name=~\"$cluster\",bucket=~\"$bucket\",state=\"replica\",instance=~\"$node\"}[$__rate_interval]))",
       "legendFormat": "{{bucket}}"
      }
     ]
    },
    {
     "title": "vBucket (Pending) Rejected Ops / sec",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 68 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "sum without(instance) (rate(kv_vb_ops_reject{cluster_name=~\"$cluster\",bucket=~\"$bucket\",state=\"pending\",instance=~\"$node\"}[$__rate_interval]))",
       "legendFormat": "{{bucket}}"
      }
     ]
    }
   ]
  },
  {
   "title": "vBucket Memory and Disk",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 },
   "collapsed": true,
   "panels": [
    {
     "title": "vBucket (Active) Memory",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 33 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "sum without(instance) (kv_vb_itm_memory_bytes{cluster_name=~\"$cluster\",bucket=~\"$bucket\",state=\"active\",instance=~\"$node\"})",
       "legendFormat": "{{bucket}}"
      }
     ]
    },
    {
     "title": "vBucket (Replica) Memory",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 33 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "sum without(instance) (kv_vb_itm_memory_bytes{cluster_name=~\"$cluster\",bucket=~\"$bucket\",state=\"replica\",instance=~\"$node\"})",
       "legendFormat": "{{bucket}}"
      }
     ]
    },
    {
     "title": "vBucket (Pending) Memory",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 33 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "sum without(instance) (kv_vb_itm_memory_bytes{cluster_name=~\"$cluster\",bucket=~\"$bucket\",state=\"pending\",instance=~\"$node\"})",
       "legendFormat": "{{bucket}}"
      }
     ]
    },
    {
     "title": "vBucket (Active) Uncompressed Memory",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 39 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "sum without(instance) (kv_vb_itm_memory_uncompressed_bytes{cluster_name=~\"$cluster\",bucket=~\"$bucket\",state=\"active\",instance=~\"$node\"})",
       "legendFormat": "{{bucket}}"
      }
     ]
    },
    {
     "title": "vBucket (Replica) Memory Uncompressed",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 39 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "sum without(instance) (kv_vb_itm_memory_uncompressed_bytes{cluster_name=~\"$cluster\",bucket=~\"$bucket\",state=\"replica\",instance=~\"$node\"})",
       "legendFormat": "{{bucket}}"
      }
     ]
    },
    {
     "title": "vBucket (Pending) Memory Uncompressed",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 39 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "sum without(instance) (kv_vb_itm_memory_uncompressed_bytes{cluster_name=~\"$cluster\",bucket=~\"$bucket\",state=\"pending\",instance=~\"$node\"})",
       "legendFormat": "{{bucket}}"
      }
     ]
    },
    {
     "title": "vBucket (Active) Metadata Disk",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 45 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "sum without(instance) (kv_vb_meta_data_disk_bytes{cluster_name=~\"$cluster\",bucket=~\"$bucket\",state=\"active\",instance=~\"$node\"})",
       "legendFormat": "{{bucket}}"
      }
     ]
    },
    {
     "title": "vBucket (Replica) Metadata Disk",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 45 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "sum without(instance) (kv_vb_meta_data_disk_bytes{cluster_name=~\"$cluster\",bucket=~\"$bucket\",state=\"replica\",instance=~\"$node\"})",
       "legendFormat": "{{bucket}}"
      }
     ]
    },
    {
     "title": "vBucket (Pending) Metadata Disk",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 45 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "sum without(instance) (kv_vb_meta_data_disk_bytes{cluster_name=~\"$cluster\",bucket=~\"$bucket\",state=\"pending\",instance=~\"$node\"})",
       "legendFormat": "{{bucket}}"
      }
     ]
    },
    {
     "title": "vBucket (Active) Metadata Memory",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 51 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "sum without(instance) (kv_vb_meta_data_memory_bytes{cluster_name=~\"$cluster\",bucket=~\"$bucket\",state=\"active\",instance=~\"$node\"})",
       "legendFormat": "{{bucket}}"
      }
     ]
    },
    {
     "title": "vBucket (Replica) Metadata Memory",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 51 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "sum without(instance) (kv_vb_meta_data_memory_bytes{cluster_name=~\"$cluster\",bucket=~\"$bucket\",state=\"replica\",instance=~\"$node\"})",
       "legendFormat": "{{bucket}}"
      }
     ]
    },
    {
     "title": "vBucket (Pending) Metadata Memory",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 51 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "sum without(instance) (kv_vb_meta_data_memory_bytes{cluster_name=~\"$cluster\",bucket=~\"$bucket\",state=\"pending\",instance=~\"$node\"})",
       "legendFormat": "{{bucket}}"
      }
     ]
    }
   ]
  },
  {
   "title": "vBucket Checkpoints",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 },
   "collapsed": true,
   "panels": [
    {
     "title": "vBucket (Active) Checkpoint Memory",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 34 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "sum without(instance) (kv_vb_checkpoint_memory_bytes{cluster_name=~\"$cluster\",bucket=~\"$bucket\",state=\"active\",instance=~\"$node\"})",
       "legendFormat": "{{bucket}}"
      }
     ]
    },
    {
     "title": "vBucket (Replica) Checkpoint Memory",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 34 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "sum without(instance) (kv_vb_checkpoint_memory_bytes{cluster_name=~\"$cluster\",bucket=~\"$bucket\",state=\"replica\",instance=~\"$node\"})",
       "legendFormat": "{{bucket}}"
      }
     ]
    },
    {
     "title": "vBucket (Pending) Checkpoint Memory",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 34 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "sum without(instance) (kv_vb_checkpoint_memory_bytes{cluster_name=~\"$cluster\",bucket=~\"$bucket\",state=\"pending\",instance=~\"$node\"})",
       "legendFormat": "{{bucket}}"
      }
     ]
    },
    {
     "title": "vBucket (Active) Checkpoint Memory Overhead",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 40 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "sum without(instance) (kv_vb_checkpoint_memory_overhead_bytes{cluster_name=~\"$cluster\",bucket=~\"$bucket\",state=\"active\",instance=~\"$node\"})",
       "legendFormat": "{{bucket}}"
      }
     ]
    },
    {
     "title": "vBucket (Replica) Checkpoint Memory Overhead",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 40 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "sum without(instance) (kv_vb_checkpoint_memory_overhead_bytes{cluster_name=~\"$cluster\",bucket=~\"$bucket\",state=\"replica\",instance=~\"$node\"})",
       "legendFormat": "{{bucket}}"
      }
     ]
    },
    {
     "title": "vBucket (Pending) Checkpoint Memory Overhead",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 40 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "sum without(instance) (kv_vb_checkpoint_memory_overhead_bytes{cluster_name=~\"$cluster\",bucket=~\"$bucket\",state=\"pending\",instance=~\"$node\"})",
       "legendFormat": "{{bucket}}"
      }
     ]
    },
    {
     "title": "vBucket (Active) Checkpoint Unreferenced Memory",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 46 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "sum without(instance) (kv_vb_checkpoint_memory_unreferenced_bytes{cluster_name=~\"$cluster\",bucket=~\"$bucket\",state=\"active\",instance=~\"$node\"})",
       "legendFormat": "{{bucket}}"
      }
     ]
    },
    {
     "title": "vBucket (Replica) Checkpoint Unreferenced Memory",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 46 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "sum without(instance) (kv_vb_checkpoint_memory_unreferenced_bytes{cluster_name=~\"$cluster\",bucket=~\"$bucket\",state=\"replica\",instance=~\"$node\"})",
       "legendFormat": "{{bucket}}"
      }
     ]
    },
    {
     "title": "vBucket (Pending) Checkpoint Unreferenced Memory ",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 46 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "sum without(instance) (kv_vb_checkpoint_memory_unreferenced_bytes{cluster_name=~\"$cluster\",bucket=~\"$bucket\",state=\"pending\",instance=~\"$node\"})",
       "legendFormat": "{{bucket}}"
      }
     ]
    }
   ]
  },
  {
   "title": "vBucket Queue",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 },
   "collapsed": true,
   "panels": [
    {
     "title": "vBucket (Active) Average Queue Age",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 35 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "avg without(instance) (rate(kv_vb_queue_age_seconds{cluster_name=~\"$cluster\",bucket=~\"$bucket\",state=\"active\",instance=~\"$node\"}[$__rate_interval]))",
       "legendFormat": "{{bucket}}"
      }
     ]
    },
    {
     "title": "vBucket (Replica) Average Queue Age",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 35 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "avg without(instance) (rate(kv_vb_queue_age_seconds{cluster_name=~\"$cluster\",bucket=~\"$bucket\",state=\"replica\",instance=~\"$node\"}[$__rate_interval]))",
       "legendFormat": "{{bucket}}"
      }
     ]
    },
    {
     "title": "vBucket (Pending) Average Queue Age",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 35 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "avg without(instance) (rate(kv_vb_queue_age_seconds{cluster_name=~\"$cluster\",bucket=~\"$bucket\",state=\"pending\",instance=~\"$node\"}[$__rate_interval]))",
       "legendFormat": "{{bucket}}"
      }
     ]
    },
    {
     "title": "vBucket (Active) Queue Drain / sec",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 41 },
     "fieldConfig": { "defaults": { "unit": "cps" } },
     "targets": [
      {
       "expr": "sum without(instance) (rate(kv_vb_queue_drain{cluster_name=~\"$cluster\",bucket=~\"$bucket\",state=\"active\",instance=~\"$node\"}[$__rate_interval]))",
       "legendFormat": "{{bucket}}"
      }
     ]
    },
    {
     "title": "vBucket (Replica) Queue Drain / sec",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 41 },
     "fieldConfig": { "defaults": { "unit": "cps" } },
     "targets": [
      {
       "expr": "sum without(instance) (rate(kv_vb_queue_drain{cluster_name=~\"$cluster\",bucket=~\"$bucket\",state=\"replica\",instance=~\"$node\"}[$__rate_interval]))",
       "legendFormat": "{{bucket}}"
      }
     ]
    },
    {
     "title": "vBucket (Pending) Drain / sec",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 41 },
     "fieldConfig": { "defaults": { "unit": "cps" } },
     "targets": [
      {
       "expr": "sum without(instance) (rate(kv_vb_queue_drain{cluster_name=~\"$cluster\",bucket=~\"$bucket\",state=\"pending\",instance=~\"$node\"}[$__rate_interval]))",
       "legendFormat": "{{bucket}}"
      }
     ]
    },
    {
     "title": "vBucket (Active) Queue Fill / sec",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 47 },
     "fieldConfig": { "defaults": { "unit": "cps" } },
     "targets": [
      {
       "expr": "sum without(instance) (rate(kv_vb_queue_fill{cluster_name=~\"$cluster\",bucket=~\"$bucket\",state=\"active\",instance=~\"$node\"}[$__rate_interval]))",
       "legendFormat": "{{bucket}}"
      }
     ]
    },
    {
     "title": "vBucket (Replica) Queue Fill / sec",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 47 },
     "fieldConfig": { "defaults": { "unit": "cps" } },
     "targets": [
      {
       "expr": "sum without(instance) (rate(kv_vb_queue_fill{cluster_name=~\"$cluster\",bucket=~\"$bucket\",state=\"replica\",instance=~\"$node\"}[$__rate_interval]))",
       "legendFormat": "{{bucket}}"
      }
     ]
    },
    {
     "title": "vBucket (Pending) Queue Fill / sec",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 47 },
     "fieldConfig": { "defaults": { "unit": "cps" } },
     "targets": [
      {
       "expr": "sum without(instance) (rate(kv_vb_queue_fill{cluster_name=~\"$cluster\",bucket=~\"$bucket\",state=\"pending\",instance=~\"$node\"}[$__rate_interval]))",
       "legendFormat": "{{bucket}}"
      }
     ]
    },
    {
     "title": "vBucket (Active) Queue Memory",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 53 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "sum without(instance) (rate(kv_vb_queue_memory_bytes{cluster_name=~\"$cluster\",bucket=~\"$bucket\",state=\"active\",instance=~\"$node\"}[$__rate_interval]))",
       "legendFormat": "{{bucket}}"
      }
     ]
    },
    {
     "title": "vBucket (Replica) Queue Memory",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 53 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "sum without(instance) (rate(kv_vb_queue_memory_bytes{cluster_name=~\"$cluster\",bucket=~\"$bucket\",state=\"replica\",instance=~\"$node\"}[$__rate_interval]))",
       "legendFormat": "{{bucket}}"
      }
     ]
    },
    {
     "title": "vBucket (Pending) Queue Memory",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 53 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "sum without(instance) (rate(kv_vb_queue_memory_bytes{cluster_name=~\"$cluster\",bucket=~\"$bucket\",state=\"pending\",instance=~\"$node\"}[$__rate_interval]))",
       "legendFormat": "{{bucket}}"
      }
     ]
    },
    {
     "title": "vBucket (Active) Queue Pending Memory",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 59 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "sum without(instance) (rate(kv_vb_queue_pending_bytes{cluster_name=~\"$cluster\",bucket=~\"$bucket\",state=\"active\",instance=~\"$node\"}[$__rate_interval]))",
       "legendFormat": "{{bucket}}"
      }
     ]
    },
    {
     "title": "vBucket (Replica) Queue Pending Memory",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 59 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "sum without(instance) (rate(kv_vb_queue_pending_bytes{cluster_name=~\"$cluster\",bucket=~\"$bucket\",state=\"replica\",instance=~\"$node\"}[$__rate_interval]))",
       "legendFormat": "{{bucket}}"
      }
     ]
    },
    {
     "title": "vBucket (Pending) Queue Pending Memory",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 59 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "sum without(instance) (rate(kv_vb_queue_pending_bytes{cluster_name=~\"$cluster\",bucket=~\"$bucket\",state=\"pending\",instance=~\"$node\"}[$__rate_interval]))",
       "legendFormat": "{{bucket}}"
      }
     ]
    },
    {
     "title": "vBucket (Active) Queue Size",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 65 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum without(instance) (rate(kv_vb_queue_size{cluster_name=~\"$cluster\",bucket=~\"$bucket\",state=\"active\",instance=~\"$node\"}[$__rate_interval]))",
       "legendFormat": "{{bucket}}"
      }
     ]
    },
    {
     "title": "vBucket (Replica) Queue Size",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 65 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum without(instance) (rate(kv_vb_queue_size{cluster_name=~\"$cluster\",bucket=~\"$bucket\",state=\"replica\",instance=~\"$node\"}[$__rate_interval]))",
       "legendFormat": "{{bucket}}"
      }
     ]
    },
    {
     "title": "vBucket (Pending) Queue Size",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 65 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum without(instance) (rate(kv_vb_queue_size{cluster_name=~\"$cluster\",bucket=~\"$bucket\",state=\"pending\",instance=~\"$node\"}[$__rate_interval]))",
       "legendFormat": "{{bucket}}"
      }
     ]
    }
   ]
  },
  {
   "title": "vBucket Sync",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 },
   "collapsed": true,
   "panels": [
    {
     "title": "vBucket (Active) Sync Writes Committed",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 36 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum without(instance) (rate(kv_vb_sync_write_committed_count{cluster_name=~\"$cluster\",bucket=~\"$bucket\",state=\"active\",instance=~\"$node\"}[$__rate_interval]))",
       "legendFormat": "{{bucket}}"
      }
     ]
    },
    {
     "title": "vBucket (Replica) Sync Writes Committed",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 36 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum without(instance) (rate(kv_vb_sync_write_committed_count{cluster_name=~\"$cluster\",bucket=~\"$bucket\",state=\"replica\",instance=~\"$node\"}[$__rate_interval]))",
       "legendFormat": "{{bucket}}"
      }
     ]
    },
    {
     "title": "vBucket (Active) Sync Writes Accepted",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 36 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum without(instance) (rate(kv_vb_sync_write_accepted_count{cluster_name=~\"$cluster\",bucket=~\"$bucket\",state=\"active\",instance=~\"$node\"}[$__rate_interval]))",
       "legendFormat": "{{bucket}}"
      }
     ]
    },
    {
     "title": "vBucket (Replica) Sync Writes Accepted",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 42 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum without(instance) (rate(kv_vb_sync_write_accepted_count{cluster_name=~\"$cluster\",bucket=~\"$bucket\",state=\"replica\",instance=~\"$node\"}[$__rate_interval]))",
       "legendFormat": "{{bucket}}"
      }
     ]
    },
    {
     "title": "vBucket (Active) Sync Writes Aborted",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 42 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum without(instance) (rate(kv_vb_sync_write_aborted_count{cluster_name=~\"$cluster\",bucket=~\"$bucket\",state=\"active\",instance=~\"$node\"}[$__rate_interval]))",
       "legendFormat": "{{bucket}}"
      }
     ]
    },
    {
     "title": "vBucket (Replica) Sync Writes Aborted",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 42 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum without(instance) (rate(kv_vb_sync_write_aborted_count{cluster_name=~\"$cluster\",bucket=~\"$bucket\",state=\"replica\",instance=~\"$node\"}[$__rate_interval]))",
       "legendFormat": "{{bucket}}"
      }
     ]
    },
    {
     "title": "vBucket (Active) Rollback Item Count",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 48 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum without(instance) (rate(kv_vb_rollback_item_count{cluster_name=~\"$cluster\",bucket=~\"$bucket\",state=\"active\",instance=~\"$node\"}[$__rate_interval]))",
       "legendFormat": "{{bucket}}"
      }
     ]
    },
    {
     "title": "vBucket (Replica) Rollback Item Count",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 48 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum without(instance) (rate(kv_vb_rollback_item_count{cluster_name=~\"$cluster\",bucket=~\"$bucket\",state=\"replica\",instance=~\"$node\"}[$__rate_interval]))",
       "legendFormat": "{{bucket}}"
      }
     ]
    }
   ]
  }
 ]
}